// Package blob provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package blob

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// BlobRequest Request payload for creating or updating an encrypted blob with per-device wrapped keys.
type BlobRequest struct {
	// Assertion Base64-encoded device assertion for write authorization.
	Assertion *[]byte `json:"assertion,omitempty"`

	// AuthPublicKeyHex Lowercase hex-encoded auth public key of the device for attestation. 66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256).
	AuthPublicKeyHex *string `json:"authPublicKeyHex,omitempty"`

	// BlobNonce Base64-encoded 12-byte nonce used for blob encryption.
	BlobNonce []byte `json:"blobNonce"`

	// EncryptedBlob Base64-encoded encrypted blob data using ChaCha20-Poly1305.
	EncryptedBlob []byte `json:"encryptedBlob"`

	// WrappedKeys Array of per-device wrapped encryption keys.
	WrappedKeys []WrappedKey `json:"wrappedKeys"`
}

// BlobResponse Response containing the encrypted blob, wrapped keys, and version metadata.
type BlobResponse struct {
	// BlobNonce Base64-encoded nonce used for blob encryption.
	BlobNonce []byte `json:"blobNonce"`

	// EncryptedBlob Base64-encoded encrypted blob data.
	EncryptedBlob []byte `json:"encryptedBlob"`

	// UpdatedAt ISO 8601 timestamp of the last update.
	UpdatedAt time.Time `json:"updatedAt"`

	// Version Monotonically increasing version number for optimistic locking.
	Version int32 `json:"version"`

	// WrappedKeys Array of per-device wrapped encryption keys.
	WrappedKeys []WrappedKey `json:"wrappedKeys"`
}

// HistoryDetailResponse Detailed response for a specific historical version of the blob.
type HistoryDetailResponse struct {
	// BlobNonce Base64-encoded nonce from this historical version.
	BlobNonce []byte `json:"blobNonce"`

	// CreatedAt ISO 8601 timestamp when this version was created.
	CreatedAt time.Time `json:"createdAt"`

	// EncryptedBlob Base64-encoded encrypted blob data from this historical version.
	EncryptedBlob []byte `json:"encryptedBlob"`

	// Version Version number of this historical snapshot.
	Version int32 `json:"version"`

	// WrappedKeys Per-device wrapped keys from this historical version.
	WrappedKeys []WrappedKey `json:"wrappedKeys"`
}

// HistoryEntry Summary entry for a blob version in the history list.
type HistoryEntry struct {
	// CreatedAt ISO 8601 timestamp when this version was created.
	CreatedAt time.Time `json:"createdAt"`

	// Version Version number that can be used to retrieve or restore this snapshot.
	Version int32 `json:"version"`
}

// HistoryListResponse Response containing the list of available historical versions.
type HistoryListResponse struct {
	// History List of historical blob versions, ordered by version number descending.
	History []HistoryEntry `json:"history"`
}

// WrappedKey Per-device wrapped encryption key for multi-device blob access.
type WrappedKey struct {
	// EncryptionPublicKeyHex Lowercase hex-encoded P-256 ECDH public key of the device that can unwrap this key. 66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256).
	EncryptionPublicKeyHex string `json:"encryptionPublicKeyHex"`

	// EphemeralPublicHex Lowercase hex-encoded ephemeral P-256 public key used for key wrapping. 66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256).
	EphemeralPublicHex string `json:"ephemeralPublicHex"`

	// WrappedKey Base64-encoded wrapped symmetric key encrypted with ChaCha20-Poly1305.
	WrappedKey []byte `json:"wrappedKey"`

	// WrappedKeyNonce Base64-encoded 12-byte nonce used for key wrapping.
	WrappedKeyNonce []byte `json:"wrappedKeyNonce"`
}

// BlobDeleteParams defines parameters for BlobDelete.
type BlobDeleteParams struct {
	// XDeviceAuthKey Lowercase hex-encoded auth public key of the device for attestation verification.
	XDeviceAuthKey string `json:"x-device-auth-key"`

	// XAssertion Base64-encoded device assertion proving control of the signing key.
	XAssertion string `json:"x-assertion"`
}

// BlobUpdateParams defines parameters for BlobUpdate.
type BlobUpdateParams struct {
	// IfMatch Current version ETag from the last GET or update response. Required for optimistic locking.
	IfMatch string `json:"if-match"`
}

// BlobHistoryListParams defines parameters for BlobHistoryList.
type BlobHistoryListParams struct {
	// Limit Maximum number of versions to return. Defaults to 20, maximum is 100.
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// BlobRestoreRestoreParams defines parameters for BlobRestoreRestore.
type BlobRestoreRestoreParams struct {
	// XDeviceAuthKey Lowercase hex-encoded auth public key of the device for attestation verification.
	XDeviceAuthKey string `json:"x-device-auth-key"`

	// XAssertion Base64-encoded device assertion proving control of the signing key.
	XAssertion string `json:"x-assertion"`
}

// BlobCreateJSONRequestBody defines body for BlobCreate for application/json ContentType.
type BlobCreateJSONRequestBody = BlobRequest

// BlobUpdateJSONRequestBody defines body for BlobUpdate for application/json ContentType.
type BlobUpdateJSONRequestBody = BlobRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HealthCheck request
	HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthReadyCheck request
	HealthReadyCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BlobDelete request
	BlobDelete(ctx context.Context, orgId string, params *BlobDeleteParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BlobGet request
	BlobGet(ctx context.Context, orgId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BlobCreateWithBody request with any body
	BlobCreateWithBody(ctx context.Context, orgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BlobCreate(ctx context.Context, orgId string, body BlobCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BlobUpdateWithBody request with any body
	BlobUpdateWithBody(ctx context.Context, orgId string, params *BlobUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BlobUpdate(ctx context.Context, orgId string, params *BlobUpdateParams, body BlobUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BlobHistoryList request
	BlobHistoryList(ctx context.Context, orgId string, params *BlobHistoryListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BlobHistoryVersionGet request
	BlobHistoryVersionGet(ctx context.Context, orgId string, version int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BlobRestoreRestore request
	BlobRestoreRestore(ctx context.Context, orgId string, version int32, params *BlobRestoreRestoreParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthReadyCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthReadyCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobDelete(ctx context.Context, orgId string, params *BlobDeleteParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobDeleteRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobGet(ctx context.Context, orgId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobGetRequest(c.Server, orgId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobCreateWithBody(ctx context.Context, orgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobCreateRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobCreate(ctx context.Context, orgId string, body BlobCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobCreateRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobUpdateWithBody(ctx context.Context, orgId string, params *BlobUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobUpdateRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobUpdate(ctx context.Context, orgId string, params *BlobUpdateParams, body BlobUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobUpdateRequest(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobHistoryList(ctx context.Context, orgId string, params *BlobHistoryListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobHistoryListRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobHistoryVersionGet(ctx context.Context, orgId string, version int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobHistoryVersionGetRequest(c.Server, orgId, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BlobRestoreRestore(ctx context.Context, orgId string, version int32, params *BlobRestoreRestoreParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBlobRestoreRestoreRequest(c.Server, orgId, version, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthCheckRequest generates requests for HealthCheck
func NewHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthReadyCheckRequest generates requests for HealthReadyCheck
func NewHealthReadyCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health/ready")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBlobDeleteRequest generates requests for BlobDelete
func NewBlobDeleteRequest(server string, orgId string, params *BlobDeleteParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/blob", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-device-auth-key", params.XDeviceAuthKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-device-auth-key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "x-assertion", params.XAssertion, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-assertion", headerParam1)

	}

	return req, nil
}

// NewBlobGetRequest generates requests for BlobGet
func NewBlobGetRequest(server string, orgId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/blob", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBlobCreateRequest calls the generic BlobCreate builder with application/json body
func NewBlobCreateRequest(server string, orgId string, body BlobCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBlobCreateRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewBlobCreateRequestWithBody generates requests for BlobCreate with any type of body
func NewBlobCreateRequestWithBody(server string, orgId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/blob", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBlobUpdateRequest calls the generic BlobUpdate builder with application/json body
func NewBlobUpdateRequest(server string, orgId string, params *BlobUpdateParams, body BlobUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBlobUpdateRequestWithBody(server, orgId, params, "application/json", bodyReader)
}

// NewBlobUpdateRequestWithBody generates requests for BlobUpdate with any type of body
func NewBlobUpdateRequestWithBody(server string, orgId string, params *BlobUpdateParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/blob", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "if-match", params.IfMatch, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("if-match", headerParam0)

	}

	return req, nil
}

// NewBlobHistoryListRequest generates requests for BlobHistoryList
func NewBlobHistoryListRequest(server string, orgId string, params *BlobHistoryListParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/blob/history", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBlobHistoryVersionGetRequest generates requests for BlobHistoryVersionGet
func NewBlobHistoryVersionGetRequest(server string, orgId string, version int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/blob/history/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBlobRestoreRestoreRequest generates requests for BlobRestoreRestore
func NewBlobRestoreRestoreRequest(server string, orgId string, version int32, params *BlobRestoreRestoreParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int32"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/blob/restore/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "x-device-auth-key", params.XDeviceAuthKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-device-auth-key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "x-assertion", params.XAssertion, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("x-assertion", headerParam1)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HealthCheckWithResponse request
	HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error)

	// HealthReadyCheckWithResponse request
	HealthReadyCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthReadyCheckResponse, error)

	// BlobDeleteWithResponse request
	BlobDeleteWithResponse(ctx context.Context, orgId string, params *BlobDeleteParams, reqEditors ...RequestEditorFn) (*BlobDeleteResponse, error)

	// BlobGetWithResponse request
	BlobGetWithResponse(ctx context.Context, orgId string, reqEditors ...RequestEditorFn) (*BlobGetResponse, error)

	// BlobCreateWithBodyWithResponse request with any body
	BlobCreateWithBodyWithResponse(ctx context.Context, orgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BlobCreateResponse, error)

	BlobCreateWithResponse(ctx context.Context, orgId string, body BlobCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*BlobCreateResponse, error)

	// BlobUpdateWithBodyWithResponse request with any body
	BlobUpdateWithBodyWithResponse(ctx context.Context, orgId string, params *BlobUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BlobUpdateResponse, error)

	BlobUpdateWithResponse(ctx context.Context, orgId string, params *BlobUpdateParams, body BlobUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BlobUpdateResponse, error)

	// BlobHistoryListWithResponse request
	BlobHistoryListWithResponse(ctx context.Context, orgId string, params *BlobHistoryListParams, reqEditors ...RequestEditorFn) (*BlobHistoryListResponse, error)

	// BlobHistoryVersionGetWithResponse request
	BlobHistoryVersionGetWithResponse(ctx context.Context, orgId string, version int32, reqEditors ...RequestEditorFn) (*BlobHistoryVersionGetResponse, error)

	// BlobRestoreRestoreWithResponse request
	BlobRestoreRestoreWithResponse(ctx context.Context, orgId string, version int32, params *BlobRestoreRestoreParams, reqEditors ...RequestEditorFn) (*BlobRestoreRestoreResponse, error)
}

type HealthCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r HealthCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthReadyCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Status string `json:"status"`
	}
}

// Status returns HTTPResponse.Status
func (r HealthReadyCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthReadyCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BlobDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r BlobDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BlobDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BlobGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BlobResponse
}

// Status returns HTTPResponse.Status
func (r BlobGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BlobGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BlobCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *BlobResponse
}

// Status returns HTTPResponse.Status
func (r BlobCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BlobCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BlobUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BlobResponse
}

// Status returns HTTPResponse.Status
func (r BlobUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BlobUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BlobHistoryListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HistoryListResponse
}

// Status returns HTTPResponse.Status
func (r BlobHistoryListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BlobHistoryListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BlobHistoryVersionGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HistoryDetailResponse
}

// Status returns HTTPResponse.Status
func (r BlobHistoryVersionGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BlobHistoryVersionGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BlobRestoreRestoreResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BlobResponse
	JSON201      *BlobResponse
}

// Status returns HTTPResponse.Status
func (r BlobRestoreRestoreResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BlobRestoreRestoreResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// HealthCheckWithResponse request returning *HealthCheckResponse
func (c *ClientWithResponses) HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error) {
	rsp, err := c.HealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckResponse(rsp)
}

// HealthReadyCheckWithResponse request returning *HealthReadyCheckResponse
func (c *ClientWithResponses) HealthReadyCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthReadyCheckResponse, error) {
	rsp, err := c.HealthReadyCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthReadyCheckResponse(rsp)
}

// BlobDeleteWithResponse request returning *BlobDeleteResponse
func (c *ClientWithResponses) BlobDeleteWithResponse(ctx context.Context, orgId string, params *BlobDeleteParams, reqEditors ...RequestEditorFn) (*BlobDeleteResponse, error) {
	rsp, err := c.BlobDelete(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobDeleteResponse(rsp)
}

// BlobGetWithResponse request returning *BlobGetResponse
func (c *ClientWithResponses) BlobGetWithResponse(ctx context.Context, orgId string, reqEditors ...RequestEditorFn) (*BlobGetResponse, error) {
	rsp, err := c.BlobGet(ctx, orgId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobGetResponse(rsp)
}

// BlobCreateWithBodyWithResponse request with arbitrary body returning *BlobCreateResponse
func (c *ClientWithResponses) BlobCreateWithBodyWithResponse(ctx context.Context, orgId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BlobCreateResponse, error) {
	rsp, err := c.BlobCreateWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobCreateResponse(rsp)
}

func (c *ClientWithResponses) BlobCreateWithResponse(ctx context.Context, orgId string, body BlobCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*BlobCreateResponse, error) {
	rsp, err := c.BlobCreate(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobCreateResponse(rsp)
}

// BlobUpdateWithBodyWithResponse request with arbitrary body returning *BlobUpdateResponse
func (c *ClientWithResponses) BlobUpdateWithBodyWithResponse(ctx context.Context, orgId string, params *BlobUpdateParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BlobUpdateResponse, error) {
	rsp, err := c.BlobUpdateWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobUpdateResponse(rsp)
}

func (c *ClientWithResponses) BlobUpdateWithResponse(ctx context.Context, orgId string, params *BlobUpdateParams, body BlobUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BlobUpdateResponse, error) {
	rsp, err := c.BlobUpdate(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobUpdateResponse(rsp)
}

// BlobHistoryListWithResponse request returning *BlobHistoryListResponse
func (c *ClientWithResponses) BlobHistoryListWithResponse(ctx context.Context, orgId string, params *BlobHistoryListParams, reqEditors ...RequestEditorFn) (*BlobHistoryListResponse, error) {
	rsp, err := c.BlobHistoryList(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobHistoryListResponse(rsp)
}

// BlobHistoryVersionGetWithResponse request returning *BlobHistoryVersionGetResponse
func (c *ClientWithResponses) BlobHistoryVersionGetWithResponse(ctx context.Context, orgId string, version int32, reqEditors ...RequestEditorFn) (*BlobHistoryVersionGetResponse, error) {
	rsp, err := c.BlobHistoryVersionGet(ctx, orgId, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobHistoryVersionGetResponse(rsp)
}

// BlobRestoreRestoreWithResponse request returning *BlobRestoreRestoreResponse
func (c *ClientWithResponses) BlobRestoreRestoreWithResponse(ctx context.Context, orgId string, version int32, params *BlobRestoreRestoreParams, reqEditors ...RequestEditorFn) (*BlobRestoreRestoreResponse, error) {
	rsp, err := c.BlobRestoreRestore(ctx, orgId, version, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBlobRestoreRestoreResponse(rsp)
}

// ParseHealthCheckResponse parses an HTTP response from a HealthCheckWithResponse call
func ParseHealthCheckResponse(rsp *http.Response) (*HealthCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseHealthReadyCheckResponse parses an HTTP response from a HealthReadyCheckWithResponse call
func ParseHealthReadyCheckResponse(rsp *http.Response) (*HealthReadyCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthReadyCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status string `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBlobDeleteResponse parses an HTTP response from a BlobDeleteWithResponse call
func ParseBlobDeleteResponse(rsp *http.Response) (*BlobDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BlobDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseBlobGetResponse parses an HTTP response from a BlobGetWithResponse call
func ParseBlobGetResponse(rsp *http.Response) (*BlobGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BlobGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BlobResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBlobCreateResponse parses an HTTP response from a BlobCreateWithResponse call
func ParseBlobCreateResponse(rsp *http.Response) (*BlobCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BlobCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest BlobResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseBlobUpdateResponse parses an HTTP response from a BlobUpdateWithResponse call
func ParseBlobUpdateResponse(rsp *http.Response) (*BlobUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BlobUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BlobResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBlobHistoryListResponse parses an HTTP response from a BlobHistoryListWithResponse call
func ParseBlobHistoryListResponse(rsp *http.Response) (*BlobHistoryListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BlobHistoryListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HistoryListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBlobHistoryVersionGetResponse parses an HTTP response from a BlobHistoryVersionGetWithResponse call
func ParseBlobHistoryVersionGetResponse(rsp *http.Response) (*BlobHistoryVersionGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BlobHistoryVersionGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HistoryDetailResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBlobRestoreRestoreResponse parses an HTTP response from a BlobRestoreRestoreWithResponse call
func ParseBlobRestoreRestoreResponse(rsp *http.Response) (*BlobRestoreRestoreResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BlobRestoreRestoreResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BlobResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest BlobResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}
