// Package keyauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package keyauth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for DeviceKeyInfoAttestationType.
const (
	AppAttest     DeviceKeyInfoAttestationType = "app_attest"
	PlayIntegrity DeviceKeyInfoAttestationType = "play_integrity"
	Software      DeviceKeyInfoAttestationType = "software"
)

// Valid indicates whether the value is a known member of the DeviceKeyInfoAttestationType enum.
func (e DeviceKeyInfoAttestationType) Valid() bool {
	switch e {
	case AppAttest:
		return true
	case PlayIntegrity:
		return true
	case Software:
		return true
	default:
		return false
	}
}

// BulkDeviceKeysRequest Bulk device keys request
type BulkDeviceKeysRequest struct {
	Emails []string `json:"emails"`
}

// BulkDeviceKeysResponse Bulk device keys response
type BulkDeviceKeysResponse struct {
	// Users Map of email to device keys
	Users map[string][]DeviceKeyInfo `json:"users"`
}

// CreatePamKeyRequest Create PAM key request
type CreatePamKeyRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`

	// SigningPublicKeyHex Lowercase hex-encoded ECDSA P-256 signing public key for PAM authentication (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256))
	SigningPublicKeyHex string `json:"signingPublicKeyHex"`
}

// DeviceKeyInfo Device key information for PAM verification
type DeviceKeyInfo struct {
	// ApproverId Approver device UUID
	ApproverId string `json:"approverId"`

	// AttestationType Type of attestation (app_attest for iOS App Attest, play_integrity for Android Play Integrity, software for non-attested keys).
	AttestationType *DeviceKeyInfoAttestationType `json:"attestationType,omitempty"`

	// AuthPublicKeyHex Lowercase hex-encoded P-256 ECDSA auth public key of the device (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256))
	AuthPublicKeyHex string  `json:"authPublicKeyHex"`
	DeviceName       *string `json:"deviceName,omitempty"`

	// EncryptionPublicKeyHex Lowercase hex-encoded P-256 ECDH encryption public key for E2E encryption (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256))
	EncryptionPublicKeyHex string  `json:"encryptionPublicKeyHex"`
	SecurityLevel          *string `json:"securityLevel,omitempty"`
}

// DeviceKeyInfoAttestationType Type of attestation (app_attest for iOS App Attest, play_integrity for Android Play Integrity, software for non-attested keys).
type DeviceKeyInfoAttestationType string

// HealthResponse Health check response
type HealthResponse struct {
	Status string `json:"status"`
}

// ListPamKeysResponse List PAM keys response
type ListPamKeysResponse struct {
	PamKeys []PamKeyInfo `json:"pamKeys"`
}

// MemberDeviceKeysResponse Member device keys response
type MemberDeviceKeysResponse struct {
	DeviceKeys []DeviceKeyInfo `json:"deviceKeys"`
}

// PamKeyActionResponse PAM key action response
type PamKeyActionResponse struct {
	Message string `json:"message"`
}

// PamKeyInfo PAM key information
type PamKeyInfo struct {
	CreatedAt   time.Time  `json:"createdAt"`
	CreatedBy   string     `json:"createdBy"`
	Description *string    `json:"description,omitempty"`
	Id          string     `json:"id"`
	LastUsedAt  *time.Time `json:"lastUsedAt,omitempty"`
	Name        string     `json:"name"`
	RevokedAt   *time.Time `json:"revokedAt,omitempty"`

	// SigningPublicKeyHex Lowercase hex-encoded ECDSA P-256 signing public key for PAM authentication (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256))
	SigningPublicKeyHex string `json:"signingPublicKeyHex"`
	Status              string `json:"status"`
	UseCount            int32  `json:"useCount"`
}

// RevokePamKeyRequest Revoke PAM key request
type RevokePamKeyRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// OrganizationMemberApproverKeysBulkGetJSONRequestBody defines body for OrganizationMemberApproverKeysBulkGet for application/json ContentType.
type OrganizationMemberApproverKeysBulkGetJSONRequestBody = BulkDeviceKeysRequest

// OrganizationPamKeysCreateJSONRequestBody defines body for OrganizationPamKeysCreate for application/json ContentType.
type OrganizationPamKeysCreateJSONRequestBody = CreatePamKeyRequest

// OrganizationPamKeyRevokeRevokeJSONRequestBody defines body for OrganizationPamKeyRevokeRevoke for application/json ContentType.
type OrganizationPamKeyRevokeRevokeJSONRequestBody = RevokePamKeyRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// OrganizationMemberApproverKeysBulkGetWithBody request with any body
	OrganizationMemberApproverKeysBulkGetWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationMemberApproverKeysBulkGet(ctx context.Context, id string, body OrganizationMemberApproverKeysBulkGetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationMemberApproverKeysGet request
	OrganizationMemberApproverKeysGet(ctx context.Context, id string, email string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationPamKeysList request
	OrganizationPamKeysList(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationPamKeysCreateWithBody request with any body
	OrganizationPamKeysCreateWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationPamKeysCreate(ctx context.Context, id string, body OrganizationPamKeysCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationPamKeyByIdDelete request
	OrganizationPamKeyByIdDelete(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationPamKeyByIdGet request
	OrganizationPamKeyByIdGet(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OrganizationPamKeyRevokeRevokeWithBody request with any body
	OrganizationPamKeyRevokeRevokeWithBody(ctx context.Context, id string, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	OrganizationPamKeyRevokeRevoke(ctx context.Context, id string, keyid string, body OrganizationPamKeyRevokeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthCheck request
	HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthReadyCheck request
	HealthReadyCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) OrganizationMemberApproverKeysBulkGetWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationMemberApproverKeysBulkGetRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationMemberApproverKeysBulkGet(ctx context.Context, id string, body OrganizationMemberApproverKeysBulkGetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationMemberApproverKeysBulkGetRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationMemberApproverKeysGet(ctx context.Context, id string, email string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationMemberApproverKeysGetRequest(c.Server, id, email)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationPamKeysList(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationPamKeysListRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationPamKeysCreateWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationPamKeysCreateRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationPamKeysCreate(ctx context.Context, id string, body OrganizationPamKeysCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationPamKeysCreateRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationPamKeyByIdDelete(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationPamKeyByIdDeleteRequest(c.Server, id, keyid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationPamKeyByIdGet(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationPamKeyByIdGetRequest(c.Server, id, keyid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationPamKeyRevokeRevokeWithBody(ctx context.Context, id string, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationPamKeyRevokeRevokeRequestWithBody(c.Server, id, keyid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OrganizationPamKeyRevokeRevoke(ctx context.Context, id string, keyid string, body OrganizationPamKeyRevokeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOrganizationPamKeyRevokeRevokeRequest(c.Server, id, keyid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthReadyCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthReadyCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewOrganizationMemberApproverKeysBulkGetRequest calls the generic OrganizationMemberApproverKeysBulkGet builder with application/json body
func NewOrganizationMemberApproverKeysBulkGetRequest(server string, id string, body OrganizationMemberApproverKeysBulkGetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationMemberApproverKeysBulkGetRequestWithBody(server, id, "application/json", bodyReader)
}

// NewOrganizationMemberApproverKeysBulkGetRequestWithBody generates requests for OrganizationMemberApproverKeysBulkGet with any type of body
func NewOrganizationMemberApproverKeysBulkGetRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/members/approver-keys/bulk", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationMemberApproverKeysGetRequest generates requests for OrganizationMemberApproverKeysGet
func NewOrganizationMemberApproverKeysGetRequest(server string, id string, email string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "email", email, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/members/%s/approver-keys", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationPamKeysListRequest generates requests for OrganizationPamKeysList
func NewOrganizationPamKeysListRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/pam-keys", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationPamKeysCreateRequest calls the generic OrganizationPamKeysCreate builder with application/json body
func NewOrganizationPamKeysCreateRequest(server string, id string, body OrganizationPamKeysCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationPamKeysCreateRequestWithBody(server, id, "application/json", bodyReader)
}

// NewOrganizationPamKeysCreateRequestWithBody generates requests for OrganizationPamKeysCreate with any type of body
func NewOrganizationPamKeysCreateRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/pam-keys", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewOrganizationPamKeyByIdDeleteRequest generates requests for OrganizationPamKeyByIdDelete
func NewOrganizationPamKeyByIdDeleteRequest(server string, id string, keyid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "keyid", keyid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/pam-keys/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationPamKeyByIdGetRequest generates requests for OrganizationPamKeyByIdGet
func NewOrganizationPamKeyByIdGetRequest(server string, id string, keyid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "keyid", keyid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/pam-keys/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOrganizationPamKeyRevokeRevokeRequest calls the generic OrganizationPamKeyRevokeRevoke builder with application/json body
func NewOrganizationPamKeyRevokeRevokeRequest(server string, id string, keyid string, body OrganizationPamKeyRevokeRevokeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewOrganizationPamKeyRevokeRevokeRequestWithBody(server, id, keyid, "application/json", bodyReader)
}

// NewOrganizationPamKeyRevokeRevokeRequestWithBody generates requests for OrganizationPamKeyRevokeRevoke with any type of body
func NewOrganizationPamKeyRevokeRevokeRequestWithBody(server string, id string, keyid string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "keyid", keyid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/organizations/%s/pam-keys/%s/revoke", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthCheckRequest generates requests for HealthCheck
func NewHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthReadyCheckRequest generates requests for HealthReadyCheck
func NewHealthReadyCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health/ready")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// OrganizationMemberApproverKeysBulkGetWithBodyWithResponse request with any body
	OrganizationMemberApproverKeysBulkGetWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationMemberApproverKeysBulkGetResponse, error)

	OrganizationMemberApproverKeysBulkGetWithResponse(ctx context.Context, id string, body OrganizationMemberApproverKeysBulkGetJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationMemberApproverKeysBulkGetResponse, error)

	// OrganizationMemberApproverKeysGetWithResponse request
	OrganizationMemberApproverKeysGetWithResponse(ctx context.Context, id string, email string, reqEditors ...RequestEditorFn) (*OrganizationMemberApproverKeysGetResponse, error)

	// OrganizationPamKeysListWithResponse request
	OrganizationPamKeysListWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*OrganizationPamKeysListResponse, error)

	// OrganizationPamKeysCreateWithBodyWithResponse request with any body
	OrganizationPamKeysCreateWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationPamKeysCreateResponse, error)

	OrganizationPamKeysCreateWithResponse(ctx context.Context, id string, body OrganizationPamKeysCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationPamKeysCreateResponse, error)

	// OrganizationPamKeyByIdDeleteWithResponse request
	OrganizationPamKeyByIdDeleteWithResponse(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*OrganizationPamKeyByIdDeleteResponse, error)

	// OrganizationPamKeyByIdGetWithResponse request
	OrganizationPamKeyByIdGetWithResponse(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*OrganizationPamKeyByIdGetResponse, error)

	// OrganizationPamKeyRevokeRevokeWithBodyWithResponse request with any body
	OrganizationPamKeyRevokeRevokeWithBodyWithResponse(ctx context.Context, id string, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationPamKeyRevokeRevokeResponse, error)

	OrganizationPamKeyRevokeRevokeWithResponse(ctx context.Context, id string, keyid string, body OrganizationPamKeyRevokeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationPamKeyRevokeRevokeResponse, error)

	// HealthCheckWithResponse request
	HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error)

	// HealthReadyCheckWithResponse request
	HealthReadyCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthReadyCheckResponse, error)
}

type OrganizationMemberApproverKeysBulkGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BulkDeviceKeysResponse
}

// Status returns HTTPResponse.Status
func (r OrganizationMemberApproverKeysBulkGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationMemberApproverKeysBulkGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationMemberApproverKeysGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MemberDeviceKeysResponse
}

// Status returns HTTPResponse.Status
func (r OrganizationMemberApproverKeysGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationMemberApproverKeysGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationPamKeysListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListPamKeysResponse
}

// Status returns HTTPResponse.Status
func (r OrganizationPamKeysListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationPamKeysListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationPamKeysCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *PamKeyInfo
}

// Status returns HTTPResponse.Status
func (r OrganizationPamKeysCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationPamKeysCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationPamKeyByIdDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PamKeyActionResponse
}

// Status returns HTTPResponse.Status
func (r OrganizationPamKeyByIdDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationPamKeyByIdDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationPamKeyByIdGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PamKeyInfo
}

// Status returns HTTPResponse.Status
func (r OrganizationPamKeyByIdGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationPamKeyByIdGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OrganizationPamKeyRevokeRevokeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PamKeyActionResponse
}

// Status returns HTTPResponse.Status
func (r OrganizationPamKeyRevokeRevokeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OrganizationPamKeyRevokeRevokeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthReadyCheckResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthReadyCheckResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthReadyCheckResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// OrganizationMemberApproverKeysBulkGetWithBodyWithResponse request with arbitrary body returning *OrganizationMemberApproverKeysBulkGetResponse
func (c *ClientWithResponses) OrganizationMemberApproverKeysBulkGetWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationMemberApproverKeysBulkGetResponse, error) {
	rsp, err := c.OrganizationMemberApproverKeysBulkGetWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationMemberApproverKeysBulkGetResponse(rsp)
}

func (c *ClientWithResponses) OrganizationMemberApproverKeysBulkGetWithResponse(ctx context.Context, id string, body OrganizationMemberApproverKeysBulkGetJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationMemberApproverKeysBulkGetResponse, error) {
	rsp, err := c.OrganizationMemberApproverKeysBulkGet(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationMemberApproverKeysBulkGetResponse(rsp)
}

// OrganizationMemberApproverKeysGetWithResponse request returning *OrganizationMemberApproverKeysGetResponse
func (c *ClientWithResponses) OrganizationMemberApproverKeysGetWithResponse(ctx context.Context, id string, email string, reqEditors ...RequestEditorFn) (*OrganizationMemberApproverKeysGetResponse, error) {
	rsp, err := c.OrganizationMemberApproverKeysGet(ctx, id, email, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationMemberApproverKeysGetResponse(rsp)
}

// OrganizationPamKeysListWithResponse request returning *OrganizationPamKeysListResponse
func (c *ClientWithResponses) OrganizationPamKeysListWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*OrganizationPamKeysListResponse, error) {
	rsp, err := c.OrganizationPamKeysList(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationPamKeysListResponse(rsp)
}

// OrganizationPamKeysCreateWithBodyWithResponse request with arbitrary body returning *OrganizationPamKeysCreateResponse
func (c *ClientWithResponses) OrganizationPamKeysCreateWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationPamKeysCreateResponse, error) {
	rsp, err := c.OrganizationPamKeysCreateWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationPamKeysCreateResponse(rsp)
}

func (c *ClientWithResponses) OrganizationPamKeysCreateWithResponse(ctx context.Context, id string, body OrganizationPamKeysCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationPamKeysCreateResponse, error) {
	rsp, err := c.OrganizationPamKeysCreate(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationPamKeysCreateResponse(rsp)
}

// OrganizationPamKeyByIdDeleteWithResponse request returning *OrganizationPamKeyByIdDeleteResponse
func (c *ClientWithResponses) OrganizationPamKeyByIdDeleteWithResponse(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*OrganizationPamKeyByIdDeleteResponse, error) {
	rsp, err := c.OrganizationPamKeyByIdDelete(ctx, id, keyid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationPamKeyByIdDeleteResponse(rsp)
}

// OrganizationPamKeyByIdGetWithResponse request returning *OrganizationPamKeyByIdGetResponse
func (c *ClientWithResponses) OrganizationPamKeyByIdGetWithResponse(ctx context.Context, id string, keyid string, reqEditors ...RequestEditorFn) (*OrganizationPamKeyByIdGetResponse, error) {
	rsp, err := c.OrganizationPamKeyByIdGet(ctx, id, keyid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationPamKeyByIdGetResponse(rsp)
}

// OrganizationPamKeyRevokeRevokeWithBodyWithResponse request with arbitrary body returning *OrganizationPamKeyRevokeRevokeResponse
func (c *ClientWithResponses) OrganizationPamKeyRevokeRevokeWithBodyWithResponse(ctx context.Context, id string, keyid string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*OrganizationPamKeyRevokeRevokeResponse, error) {
	rsp, err := c.OrganizationPamKeyRevokeRevokeWithBody(ctx, id, keyid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationPamKeyRevokeRevokeResponse(rsp)
}

func (c *ClientWithResponses) OrganizationPamKeyRevokeRevokeWithResponse(ctx context.Context, id string, keyid string, body OrganizationPamKeyRevokeRevokeJSONRequestBody, reqEditors ...RequestEditorFn) (*OrganizationPamKeyRevokeRevokeResponse, error) {
	rsp, err := c.OrganizationPamKeyRevokeRevoke(ctx, id, keyid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOrganizationPamKeyRevokeRevokeResponse(rsp)
}

// HealthCheckWithResponse request returning *HealthCheckResponse
func (c *ClientWithResponses) HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckResponse, error) {
	rsp, err := c.HealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckResponse(rsp)
}

// HealthReadyCheckWithResponse request returning *HealthReadyCheckResponse
func (c *ClientWithResponses) HealthReadyCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthReadyCheckResponse, error) {
	rsp, err := c.HealthReadyCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthReadyCheckResponse(rsp)
}

// ParseOrganizationMemberApproverKeysBulkGetResponse parses an HTTP response from a OrganizationMemberApproverKeysBulkGetWithResponse call
func ParseOrganizationMemberApproverKeysBulkGetResponse(rsp *http.Response) (*OrganizationMemberApproverKeysBulkGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationMemberApproverKeysBulkGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BulkDeviceKeysResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseOrganizationMemberApproverKeysGetResponse parses an HTTP response from a OrganizationMemberApproverKeysGetWithResponse call
func ParseOrganizationMemberApproverKeysGetResponse(rsp *http.Response) (*OrganizationMemberApproverKeysGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationMemberApproverKeysGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MemberDeviceKeysResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseOrganizationPamKeysListResponse parses an HTTP response from a OrganizationPamKeysListWithResponse call
func ParseOrganizationPamKeysListResponse(rsp *http.Response) (*OrganizationPamKeysListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationPamKeysListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListPamKeysResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseOrganizationPamKeysCreateResponse parses an HTTP response from a OrganizationPamKeysCreateWithResponse call
func ParseOrganizationPamKeysCreateResponse(rsp *http.Response) (*OrganizationPamKeysCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationPamKeysCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PamKeyInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseOrganizationPamKeyByIdDeleteResponse parses an HTTP response from a OrganizationPamKeyByIdDeleteWithResponse call
func ParseOrganizationPamKeyByIdDeleteResponse(rsp *http.Response) (*OrganizationPamKeyByIdDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationPamKeyByIdDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PamKeyActionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseOrganizationPamKeyByIdGetResponse parses an HTTP response from a OrganizationPamKeyByIdGetWithResponse call
func ParseOrganizationPamKeyByIdGetResponse(rsp *http.Response) (*OrganizationPamKeyByIdGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationPamKeyByIdGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PamKeyInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseOrganizationPamKeyRevokeRevokeResponse parses an HTTP response from a OrganizationPamKeyRevokeRevokeWithResponse call
func ParseOrganizationPamKeyRevokeRevokeResponse(rsp *http.Response) (*OrganizationPamKeyRevokeRevokeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OrganizationPamKeyRevokeRevokeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PamKeyActionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseHealthCheckResponse parses an HTTP response from a HealthCheckWithResponse call
func ParseHealthCheckResponse(rsp *http.Response) (*HealthCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseHealthReadyCheckResponse parses an HTTP response from a HealthReadyCheckWithResponse call
func ParseHealthReadyCheckResponse(rsp *http.Response) (*HealthReadyCheckResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthReadyCheckResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
