// Package auditchain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package auditchain

import (
	"time"
)

// Defines values for AuditAttestationType.
const (
	AppAttest     AuditAttestationType = "app_attest"
	PlayIntegrity AuditAttestationType = "play_integrity"
	Software      AuditAttestationType = "software"
)

// Valid indicates whether the value is a known member of the AuditAttestationType enum.
func (e AuditAttestationType) Valid() bool {
	switch e {
	case AppAttest:
		return true
	case PlayIntegrity:
		return true
	case Software:
		return true
	default:
		return false
	}
}

// Defines values for AuditEntryType.
const (
	OfflineApproval AuditEntryType = "offline_approval"
	RequestCreated  AuditEntryType = "request_created"
	RequestResolved AuditEntryType = "request_resolved"
	Response        AuditEntryType = "response"
)

// Valid indicates whether the value is a known member of the AuditEntryType enum.
func (e AuditEntryType) Valid() bool {
	switch e {
	case OfflineApproval:
		return true
	case RequestCreated:
		return true
	case RequestResolved:
		return true
	case Response:
		return true
	default:
		return false
	}
}

// Defines values for AuditOutcome.
const (
	Rejected  AuditOutcome = "rejected"
	Responded AuditOutcome = "responded"
	Timeout   AuditOutcome = "timeout"
)

// Valid indicates whether the value is a known member of the AuditOutcome enum.
func (e AuditOutcome) Valid() bool {
	switch e {
	case Rejected:
		return true
	case Responded:
		return true
	case Timeout:
		return true
	default:
		return false
	}
}

// AuditAttestationType Type of attestation used to verify device authenticity. app_attest for iOS App Attest, play_integrity for Android Play Integrity, software for non-attested (software-only) keys.
type AuditAttestationType string

// AuditEntryType Type of event recorded in the audit chain.
type AuditEntryType string

// AuditOutcome Final outcome of a signing request resolution.
type AuditOutcome string

// AuditSyncEntry Single entry synchronized from a device's local audit chain to the server.
type AuditSyncEntry struct {
	// AuditSigningPublicKeyHex Lowercase hex-encoded P-256 ECDSA public key of the purpose-scoped audit signing key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)).
	AuditSigningPublicKeyHex string `json:"auditSigningPublicKeyHex"`

	// ChallengeContext Context information for the challenge (e.g., domain, application).
	ChallengeContext *string `json:"challengeContext,omitempty"`

	// ChallengeHash Hash of the challenge data that was signed.
	ChallengeHash *string `json:"challengeHash,omitempty"`

	// DeviceSignature Base64-encoded ECDSA P-256 signature over the entry using the device's audit signing key.
	DeviceSignature string `json:"deviceSignature"`

	// EncryptedPayloadHash Hash of the encrypted payload for verification without decryption.
	EncryptedPayloadHash string `json:"encryptedPayloadHash"`

	// EntryHash SHA256 hash of the entry for integrity verification.
	EntryHash string `json:"entryHash"`

	// EntryId Unique identifier for this audit entry.
	EntryId string `json:"entryId"`

	// EntryType Type of audit event recorded.
	EntryType string `json:"entryType"`

	// PlaintextHash Hash of the plaintext known only to the device.
	PlaintextHash string `json:"plaintextHash"`

	// PrevHash Hash of the previous entry, creating a cryptographic chain.
	PrevHash *string `json:"prevHash,omitempty"`

	// RequestHash Hash of the associated signing request.
	RequestHash *string `json:"requestHash,omitempty"`

	// Sequence Monotonically increasing sequence number within the device chain.
	Sequence int64 `json:"sequence"`

	// Timestamp ISO 8601 timestamp when the entry was created on the device.
	Timestamp string `json:"timestamp"`
}

// AuditSyncRequest Request to synchronize device audit entries to the server.
type AuditSyncRequest struct {
	// Attestation Base64-encoded device attestation for authenticity.
	Attestation *string `json:"attestation,omitempty"`

	// AttestationType Type of attestation (app_attest for iOS App Attest, play_integrity for Android Play Integrity, software for non-attested keys).
	AttestationType *AuditAttestationType `json:"attestationType,omitempty"`

	// ChainTip Hash of the last entry known by the server for incremental sync.
	ChainTip string `json:"chainTip"`

	// DeviceId Unique identifier of the device submitting entries.
	DeviceId string `json:"deviceId"`

	// Entries New audit entries to synchronize.
	Entries []AuditSyncEntry `json:"entries"`

	// OrgId Organization ID for enterprise audit aggregation.
	OrgId string `json:"orgId"`
}

// AuditSyncResult Result of an audit chain synchronization operation.
type AuditSyncResult struct {
	// EntriesSynced Number of entries successfully synchronized.
	EntriesSynced int32 `json:"entriesSynced"`

	// Errors Error messages for entries that failed to sync.
	Errors []string `json:"errors"`

	// LastSyncedSequence Sequence number of the last successfully synced entry.
	LastSyncedSequence *int64 `json:"lastSyncedSequence,omitempty"`

	// ServerReceivedAt Server timestamp when the sync was processed.
	ServerReceivedAt time.Time `json:"serverReceivedAt"`
}

// ChainExport Complete export of audit chain data for offline verification.
type ChainExport struct {
	// Commitments Customer commitments published during the time range.
	Commitments *[]CustomerCommitment `json:"commitments,omitempty"`

	// DeviceEntries All device chain entries in the time range.
	DeviceEntries []DeviceChainEntry `json:"deviceEntries"`

	// ExportedAt Timestamp when the export was created.
	ExportedAt time.Time `json:"exportedAt"`

	// FromTime Start of the time range included in the export.
	FromTime time.Time `json:"fromTime"`

	// MerkleTrees Merkle trees created during the time range.
	MerkleTrees []MerkleTree `json:"merkleTrees"`

	// OrgId Organization ID for the exported data.
	OrgId string `json:"orgId"`

	// RequestEntries All request chain entries in the time range.
	RequestEntries []RequestChainEntry `json:"requestEntries"`

	// ToTime End of the time range included in the export.
	ToTime time.Time `json:"toTime"`
}

// ChainSummary Summary statistics for an organization's audit chain.
type ChainSummary struct {
	// DeviceCount Number of unique devices with entries.
	DeviceCount int64 `json:"deviceCount"`

	// DeviceEntryCount Total number of device chain entries.
	DeviceEntryCount int64 `json:"deviceEntryCount"`

	// LastDeviceEntryAt Timestamp of the most recent device entry.
	LastDeviceEntryAt *time.Time `json:"lastDeviceEntryAt,omitempty"`

	// LastMerkleTreeAt Timestamp of the most recent Merkle tree.
	LastMerkleTreeAt *time.Time `json:"lastMerkleTreeAt,omitempty"`

	// LastRequestEntryAt Timestamp of the most recent request entry.
	LastRequestEntryAt *time.Time `json:"lastRequestEntryAt,omitempty"`

	// MerkleTreeCount Number of Merkle trees created.
	MerkleTreeCount int64 `json:"merkleTreeCount"`

	// OrgId Organization ID for the summary.
	OrgId string `json:"orgId"`

	// RequestEntryCount Total number of request chain entries.
	RequestEntryCount int64 `json:"requestEntryCount"`
}

// CommitmentWebhookPayload Webhook payload sent when a new commitment is published.
type CommitmentWebhookPayload struct {
	// Commitment The customer commitment that was published.
	Commitment CustomerCommitment `json:"commitment"`

	// InclusionProofUrl URL to fetch the inclusion proof for this commitment.
	InclusionProofUrl string `json:"inclusionProofUrl"`
}

// CustomerCommitment Commitment to the current state of an organization's audit chain.
type CustomerCommitment struct {
	// DeviceCount Number of devices included in this tree.
	DeviceCount int32 `json:"deviceCount"`

	// EntryCount Total number of entries in this tree.
	EntryCount int64 `json:"entryCount"`

	// MerkleRoot Base64-encoded Merkle root hash.
	MerkleRoot []byte `json:"merkleRoot"`

	// OrgId Organization ID for this commitment.
	OrgId string `json:"orgId"`

	// Timestamp Timestamp when the commitment was created.
	Timestamp time.Time `json:"timestamp"`

	// TreeId Unique identifier for the Merkle tree.
	TreeId string `json:"treeId"`

	// TreeSequence Sequence number of this tree for the organization.
	TreeSequence int64 `json:"treeSequence"`
}

// DeviceChainEntry Single entry in a device's audit chain with cryptographic signatures.
type DeviceChainEntry struct {
	// AttestationData Base64-encoded device attestation.
	AttestationData *[]byte `json:"attestationData,omitempty"`

	// AttestationType Type of attestation used (app_attest, play_integrity, or software for non-attested keys).
	AttestationType *AuditAttestationType `json:"attestationType,omitempty"`

	// AuditSigningPublicKeyHex Lowercase hex-encoded P-256 ECDSA public key of the purpose-scoped audit signing key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)).
	AuditSigningPublicKeyHex *string `json:"auditSigningPublicKeyHex,omitempty"`

	// ChallengeContext Context for the challenge (domain, application).
	ChallengeContext *string `json:"challengeContext,omitempty"`

	// ChallengeHash Base64-encoded hash of the signing challenge.
	ChallengeHash *[]byte `json:"challengeHash,omitempty"`

	// DeviceId Device that created this entry.
	DeviceId string `json:"deviceId"`

	// DeviceSignature Base64-encoded ECDSA P-256 signature by the device's audit signing key.
	DeviceSignature []byte `json:"deviceSignature"`

	// EncryptedPayloadHash Base64-encoded hash of the encrypted payload.
	EncryptedPayloadHash []byte `json:"encryptedPayloadHash"`

	// EntryHash Base64-encoded SHA256 hash of the entry.
	EntryHash []byte `json:"entryHash"`

	// EntryId Unique identifier for this entry.
	EntryId string `json:"entryId"`

	// EntryType Type of audit event recorded.
	EntryType AuditEntryType `json:"entryType"`

	// OrgId Organization ID for enterprise aggregation.
	OrgId string `json:"orgId"`

	// PlaintextHash Base64-encoded hash of the plaintext.
	PlaintextHash []byte `json:"plaintextHash"`

	// PrevHash Base64-encoded hash of the previous entry.
	PrevHash *[]byte `json:"prevHash,omitempty"`

	// RequestHash Base64-encoded hash of the associated request.
	RequestHash *[]byte `json:"requestHash,omitempty"`

	// Sequence Sequence number within the device chain.
	Sequence int64 `json:"sequence"`

	// SyncBatchId Batch ID for the sync operation.
	SyncBatchId *string `json:"syncBatchId,omitempty"`

	// SyncedAt Timestamp when synced to server.
	SyncedAt *time.Time `json:"syncedAt,omitempty"`

	// Timestamp Timestamp when the entry was created.
	Timestamp time.Time `json:"timestamp"`
}

// DeviceChainTip Latest entry reference for a device chain in a Merkle tree.
type DeviceChainTip struct {
	// DeviceId Device ID for this chain tip.
	DeviceId string `json:"deviceId"`

	// Hash Base64-encoded hash of the latest entry.
	Hash []byte `json:"hash"`

	// Sequence Sequence number of the latest entry.
	Sequence int64 `json:"sequence"`

	// Timestamp Timestamp of the latest entry.
	Timestamp *string `json:"timestamp,omitempty"`
}

// InclusionProof Cryptographic proof that an entry is included in a Merkle tree.
type InclusionProof struct {
	// EntryHash Base64-encoded hash of the entry being proven.
	EntryHash []byte `json:"entryHash"`

	// LeafIndex Index of the entry in the tree.
	LeafIndex int64 `json:"leafIndex"`

	// MerkleRoot Base64-encoded Merkle root.
	MerkleRoot []byte `json:"merkleRoot"`

	// SiblingHashes Base64-encoded sibling hashes for proof verification.
	SiblingHashes [][]byte `json:"siblingHashes"`

	// TreeId Merkle tree containing the entry.
	TreeId string `json:"treeId"`

	// TreeSize Total number of leaves in the tree.
	TreeSize int64 `json:"treeSize"`
}

// MerkleProof Raw Merkle tree proof data for reconstruction.
type MerkleProof struct {
	// Depth Depth of the Merkle tree.
	Depth int32 `json:"depth"`

	// Leaves Base64-encoded leaf hashes.
	Leaves [][]byte `json:"leaves"`
}

// MerkleTree Merkle tree that rolls up device and request chains for verification.
type MerkleTree struct {
	// CustomerWebhookSentAt Timestamp when webhook was sent to customer.
	CustomerWebhookSentAt *time.Time `json:"customerWebhookSentAt,omitempty"`

	// DeviceChainTips Chain tips for all devices in this tree.
	DeviceChainTips []DeviceChainTip `json:"deviceChainTips"`

	// MerkleProofData Proof data for tree reconstruction.
	MerkleProofData *MerkleProof `json:"merkleProofData,omitempty"`

	// MerkleRoot Base64-encoded Merkle root hash.
	MerkleRoot []byte `json:"merkleRoot"`

	// OrgId Organization ID for this tree.
	OrgId string `json:"orgId"`

	// PrevRoot Base64-encoded previous Merkle root for chaining.
	PrevRoot *[]byte `json:"prevRoot,omitempty"`

	// RequestChainTipHash Base64-encoded hash of the request chain tip.
	RequestChainTipHash []byte `json:"requestChainTipHash"`

	// RequestChainTipSequence Sequence of the request chain tip.
	RequestChainTipSequence int64 `json:"requestChainTipSequence"`

	// Sequence Sequence number for this tree.
	Sequence int64 `json:"sequence"`

	// Timestamp Timestamp when the tree was created.
	Timestamp time.Time `json:"timestamp"`

	// TotalEntryCount Total entries included in this tree.
	TotalEntryCount *int64 `json:"totalEntryCount,omitempty"`

	// TreeId Unique identifier for this tree.
	TreeId string `json:"treeId"`
}

// RequestChainEntry Entry in the request chain tracking signing request lifecycle.
type RequestChainEntry struct {
	// EncryptedPayloadHash Base64-encoded hash of the encrypted payload.
	EncryptedPayloadHash *[]byte `json:"encryptedPayloadHash,omitempty"`

	// EntryHash Base64-encoded SHA256 hash of the entry.
	EntryHash []byte `json:"entryHash"`

	// EntryId Unique identifier for this entry.
	EntryId string `json:"entryId"`

	// EntryType Type of request event recorded.
	EntryType AuditEntryType `json:"entryType"`

	// ExpiresAt When the request expired.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// OrgId Organization ID for this entry.
	OrgId string `json:"orgId"`

	// Outcome Final outcome of the request.
	Outcome *AuditOutcome `json:"outcome,omitempty"`

	// PlaintextHash Base64-encoded hash of the plaintext.
	PlaintextHash *[]byte `json:"plaintextHash,omitempty"`

	// PrevHash Base64-encoded hash of the previous entry.
	PrevHash *[]byte `json:"prevHash,omitempty"`

	// RequestEntryHash Base64-encoded hash linking to request creation entry.
	RequestEntryHash *[]byte `json:"requestEntryHash,omitempty"`

	// RequestId ID of the signing request.
	RequestId *string `json:"requestId,omitempty"`

	// RequesterContext HTTP context from the requester.
	RequesterContext *RequesterContext `json:"requesterContext,omitempty"`

	// RequesterId ID of the requester.
	RequesterId *string `json:"requesterId,omitempty"`

	// Sequence Sequence number in the request chain.
	Sequence int64 `json:"sequence"`

	// SigningPublicKeyHex Lowercase hex-encoded public key of the key used for signing.
	SigningPublicKeyHex *string `json:"signingPublicKeyHex,omitempty"`

	// Timestamp Timestamp when the entry was created.
	Timestamp time.Time `json:"timestamp"`

	// WinningDeviceEntryHash Base64-encoded hash of the winning device entry.
	WinningDeviceEntryHash *[]byte `json:"winningDeviceEntryHash,omitempty"`

	// WinningDeviceId Device that responded first (for resolution entries).
	WinningDeviceId *string `json:"winningDeviceId,omitempty"`
}

// RequesterContext Sanitized HTTP context from the signing requester.
type RequesterContext struct {
	// ClientIp IP address of the requester client.
	ClientIp *string `json:"clientIp,omitempty"`

	// Origin Origin header for web requests.
	Origin *string `json:"origin,omitempty"`

	// UserAgent User-Agent header from the request.
	UserAgent *string `json:"userAgent,omitempty"`
}

// VerificationError Details of a verification failure in the audit chain.
type VerificationError struct {
	// Description Human-readable error description.
	Description string `json:"description"`

	// EntryId Entry ID where the error occurred.
	EntryId *string `json:"entryId,omitempty"`

	// ErrorType Type of verification failure.
	ErrorType string `json:"errorType"`

	// Sequence Sequence number of the problematic entry.
	Sequence *int64 `json:"sequence,omitempty"`
}

// VerificationResult Result of verifying an audit chain's integrity.
type VerificationResult struct {
	// EntriesCount Number of entries that were verified.
	EntriesCount int64 `json:"entriesCount"`

	// Errors List of verification errors if invalid.
	Errors *[]VerificationError `json:"errors,omitempty"`

	// Valid Whether the chain passed all verification checks.
	Valid bool `json:"valid"`

	// Warnings Non-fatal issues found during verification.
	Warnings *[]string `json:"warnings,omitempty"`
}
