/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Type of attestation used to verify device authenticity. app_attest for iOS App Attest, play_integrity for Android Play Integrity, software for non-attested (software-only) keys.
         * @example app_attest
         * @enum {string}
         */
        AuditAttestationType: "app_attest" | "play_integrity" | "software";
        /**
         * @description Type of event recorded in the audit chain.
         * @example response
         * @enum {string}
         */
        AuditEntryType: "response" | "offline_approval" | "request_created" | "request_resolved";
        /**
         * @description Final outcome of a signing request resolution.
         * @example responded
         * @enum {string}
         */
        AuditOutcome: "responded" | "timeout" | "rejected";
        /** @description Single entry synchronized from a device's local audit chain to the server. */
        AuditSyncEntry: {
            /**
             * @description Unique identifier for this audit entry.
             * @example entry_abc123
             */
            entryId: string;
            /**
             * Format: int64
             * @description Monotonically increasing sequence number within the device chain.
             * @example 42
             */
            sequence: number;
            /**
             * @description ISO 8601 timestamp when the entry was created on the device.
             * @example 2024-01-15T12:00:00Z
             */
            timestamp: string;
            /**
             * @description SHA256 hash of the entry for integrity verification.
             * @example abc123def456...
             */
            entryHash: string;
            /**
             * @description Hash of the previous entry, creating a cryptographic chain.
             * @example xyz789ghi012...
             */
            prevHash?: string;
            /**
             * @description Type of audit event recorded.
             * @example response
             */
            entryType: string;
            /**
             * @description Hash of the associated signing request.
             * @example req_hash_123...
             */
            requestHash?: string;
            /**
             * @description Hash of the challenge data that was signed.
             * @example challenge_hash_456...
             */
            challengeHash?: string;
            /**
             * @description Context information for the challenge (e.g., domain, application).
             * @example github.com
             */
            challengeContext?: string;
            /**
             * @description Hash of the encrypted payload for verification without decryption.
             * @example enc_hash_789...
             */
            encryptedPayloadHash: string;
            /**
             * @description Hash of the plaintext known only to the device.
             * @example plain_hash_012...
             */
            plaintextHash: string;
            /**
             * @description Base64-encoded ECDSA P-256 signature over the entry using the device's audit signing key.
             * @example c2lnbmF0dXJl
             */
            deviceSignature: string;
            /**
             * @description Lowercase hex-encoded P-256 ECDSA public key of the purpose-scoped audit signing key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)).
             * @example cHVibGljS2V5
             */
            auditSigningPublicKeyHex: string;
        };
        /** @description Request to synchronize device audit entries to the server. */
        AuditSyncRequest: {
            /**
             * @description Unique identifier of the device submitting entries.
             * @example dev_abc123
             */
            deviceId: string;
            /**
             * @description Organization ID for enterprise audit aggregation.
             * @example org_xyz789
             */
            orgId: string;
            /**
             * @description Hash of the last entry known by the server for incremental sync.
             * @example tip_hash_123...
             */
            chainTip: string;
            /** @description New audit entries to synchronize. */
            entries: components["schemas"]["AuditSyncEntry"][];
            /**
             * @description Base64-encoded device attestation for authenticity.
             * @example YXR0ZXN0YXRpb24=
             */
            attestation?: string;
            /**
             * @description Type of attestation (app_attest for iOS App Attest, play_integrity for Android Play Integrity, software for non-attested keys).
             * @example app_attest
             */
            attestationType?: components["schemas"]["AuditAttestationType"];
        };
        /** @description Result of an audit chain synchronization operation. */
        AuditSyncResult: {
            /**
             * Format: int32
             * @description Number of entries successfully synchronized.
             * @example 5
             */
            entriesSynced: number;
            /**
             * @description Error messages for entries that failed to sync.
             * @example [
             *       "entry_003: invalid signature"
             *     ]
             */
            errors: string[];
            /**
             * Format: int64
             * @description Sequence number of the last successfully synced entry.
             * @example 47
             */
            lastSyncedSequence?: number;
            /**
             * Format: date-time
             * @description Server timestamp when the sync was processed.
             * @example 2024-01-15T12:00:00Z
             */
            serverReceivedAt: string;
        };
        /** @description Complete export of audit chain data for offline verification. */
        ChainExport: {
            /**
             * @description Organization ID for the exported data.
             * @example org_xyz789
             */
            orgId: string;
            /**
             * Format: date-time
             * @description Timestamp when the export was created.
             * @example 2024-01-15T12:00:00Z
             */
            exportedAt: string;
            /**
             * Format: date-time
             * @description Start of the time range included in the export.
             * @example 2024-01-01T00:00:00Z
             */
            fromTime: string;
            /**
             * Format: date-time
             * @description End of the time range included in the export.
             * @example 2024-01-31T23:59:59Z
             */
            toTime: string;
            /** @description All device chain entries in the time range. */
            deviceEntries: components["schemas"]["DeviceChainEntry"][];
            /** @description All request chain entries in the time range. */
            requestEntries: components["schemas"]["RequestChainEntry"][];
            /** @description Merkle trees created during the time range. */
            merkleTrees: components["schemas"]["MerkleTree"][];
            /** @description Customer commitments published during the time range. */
            commitments?: components["schemas"]["CustomerCommitment"][];
        };
        /** @description Summary statistics for an organization's audit chain. */
        ChainSummary: {
            /**
             * @description Organization ID for the summary.
             * @example org_xyz789
             */
            orgId: string;
            /**
             * Format: int64
             * @description Total number of device chain entries.
             * @example 1234
             */
            deviceEntryCount: number;
            /**
             * Format: int64
             * @description Number of unique devices with entries.
             * @example 15
             */
            deviceCount: number;
            /**
             * Format: int64
             * @description Total number of request chain entries.
             * @example 567
             */
            requestEntryCount: number;
            /**
             * Format: int64
             * @description Number of Merkle trees created.
             * @example 10
             */
            merkleTreeCount: number;
            /**
             * Format: date-time
             * @description Timestamp of the most recent device entry.
             * @example 2024-01-15T12:00:00Z
             */
            lastDeviceEntryAt?: string;
            /**
             * Format: date-time
             * @description Timestamp of the most recent request entry.
             * @example 2024-01-15T11:55:00Z
             */
            lastRequestEntryAt?: string;
            /**
             * Format: date-time
             * @description Timestamp of the most recent Merkle tree.
             * @example 2024-01-15T12:00:00Z
             */
            lastMerkleTreeAt?: string;
        };
        /** @description Webhook payload sent when a new commitment is published. */
        CommitmentWebhookPayload: {
            /** @description The customer commitment that was published. */
            commitment: components["schemas"]["CustomerCommitment"];
            /**
             * @description URL to fetch the inclusion proof for this commitment.
             * @example https://api.ackagent.com/v1/proofs/tree_abc123
             */
            inclusionProofUrl: string;
        };
        /** @description Commitment to the current state of an organization's audit chain. */
        CustomerCommitment: {
            /**
             * @description Unique identifier for the Merkle tree.
             * @example tree_abc123
             */
            treeId: string;
            /**
             * @description Organization ID for this commitment.
             * @example org_xyz789
             */
            orgId: string;
            /**
             * Format: byte
             * @description Base64-encoded Merkle root hash.
             * @example bWVya2xlIHJvb3Q=
             */
            merkleRoot: string;
            /**
             * Format: int64
             * @description Sequence number of this tree for the organization.
             * @example 42
             */
            treeSequence: number;
            /**
             * Format: date-time
             * @description Timestamp when the commitment was created.
             * @example 2024-01-15T12:00:00Z
             */
            timestamp: string;
            /**
             * Format: int32
             * @description Number of devices included in this tree.
             * @example 15
             */
            deviceCount: number;
            /**
             * Format: int64
             * @description Total number of entries in this tree.
             * @example 1234
             */
            entryCount: number;
        };
        /** @description Single entry in a device's audit chain with cryptographic signatures. */
        DeviceChainEntry: {
            /**
             * @description Unique identifier for this entry.
             * @example entry_abc123
             */
            entryId: string;
            /**
             * @description Organization ID for enterprise aggregation.
             * @example org_xyz789
             */
            orgId: string;
            /**
             * @description Device that created this entry.
             * @example dev_abc123
             */
            deviceId: string;
            /**
             * Format: int64
             * @description Sequence number within the device chain.
             * @example 42
             */
            sequence: number;
            /**
             * Format: date-time
             * @description Timestamp when the entry was created.
             * @example 2024-01-15T12:00:00Z
             */
            timestamp: string;
            /**
             * Format: byte
             * @description Base64-encoded SHA256 hash of the entry.
             * @example ZW50cnkgaGFzaA==
             */
            entryHash: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the previous entry.
             * @example cHJldmlvdXMgaGFzaA==
             */
            prevHash?: string;
            /** @description Type of audit event recorded. */
            entryType: components["schemas"]["AuditEntryType"];
            /**
             * Format: byte
             * @description Base64-encoded hash of the associated request.
             * @example cmVxdWVzdCBoYXNo
             */
            requestHash?: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the signing challenge.
             * @example Y2hhbGxlbmdlIGhhc2g=
             */
            challengeHash?: string;
            /**
             * @description Context for the challenge (domain, application).
             * @example github.com
             */
            challengeContext?: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the encrypted payload.
             * @example ZW5jcnlwdGVkIGhhc2g=
             */
            encryptedPayloadHash: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the plaintext.
             * @example cGxhaW50ZXh0IGhhc2g=
             */
            plaintextHash: string;
            /**
             * Format: byte
             * @description Base64-encoded ECDSA P-256 signature by the device's audit signing key.
             * @example c2lnbmF0dXJl
             */
            deviceSignature: string;
            /**
             * @description Lowercase hex-encoded P-256 ECDSA public key of the purpose-scoped audit signing key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)).
             * @example 02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2
             */
            auditSigningPublicKeyHex?: string;
            /**
             * Format: byte
             * @description Base64-encoded device attestation.
             * @example YXR0ZXN0YXRpb24=
             */
            attestationData?: string;
            /** @description Type of attestation used (app_attest, play_integrity, or software for non-attested keys). */
            attestationType?: components["schemas"]["AuditAttestationType"];
            /**
             * Format: date-time
             * @description Timestamp when synced to server.
             * @example 2024-01-15T12:00:01Z
             */
            syncedAt?: string;
            /**
             * @description Batch ID for the sync operation.
             * @example batch_abc123
             */
            syncBatchId?: string;
        };
        /** @description Latest entry reference for a device chain in a Merkle tree. */
        DeviceChainTip: {
            /**
             * @description Device ID for this chain tip.
             * @example dev_abc123
             */
            deviceId: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the latest entry.
             * @example dGlwIGhhc2g=
             */
            hash: string;
            /**
             * Format: int64
             * @description Sequence number of the latest entry.
             * @example 42
             */
            sequence: number;
            /**
             * @description Timestamp of the latest entry.
             * @example 2024-01-15T12:00:00Z
             */
            timestamp?: string;
        };
        /** @description Cryptographic proof that an entry is included in a Merkle tree. */
        InclusionProof: {
            /**
             * Format: byte
             * @description Base64-encoded hash of the entry being proven.
             * @example ZW50cnkgaGFzaA==
             */
            entryHash: string;
            /**
             * @description Merkle tree containing the entry.
             * @example tree_abc123
             */
            treeId: string;
            /**
             * Format: byte
             * @description Base64-encoded Merkle root.
             * @example bWVya2xlIHJvb3Q=
             */
            merkleRoot: string;
            /**
             * Format: int64
             * @description Index of the entry in the tree.
             * @example 42
             */
            leafIndex: number;
            /**
             * Format: int64
             * @description Total number of leaves in the tree.
             * @example 100
             */
            treeSize: number;
            /**
             * @description Base64-encoded sibling hashes for proof verification.
             * @example [
             *       "c2libGluZyAxCg==",
             *       "c2libGluZyAyCg=="
             *     ]
             */
            siblingHashes: string[];
        };
        /** @description Raw Merkle tree proof data for reconstruction. */
        MerkleProof: {
            /**
             * @description Base64-encoded leaf hashes.
             * @example [
             *       "bGVhZiAx",
             *       "bGVhZiAy"
             *     ]
             */
            leaves: string[];
            /**
             * Format: int32
             * @description Depth of the Merkle tree.
             * @example 8
             */
            depth: number;
        };
        /** @description Merkle tree that rolls up device and request chains for verification. */
        MerkleTree: {
            /**
             * @description Unique identifier for this tree.
             * @example tree_abc123
             */
            treeId: string;
            /**
             * @description Organization ID for this tree.
             * @example org_xyz789
             */
            orgId: string;
            /**
             * Format: int64
             * @description Sequence number for this tree.
             * @example 42
             */
            sequence: number;
            /**
             * Format: date-time
             * @description Timestamp when the tree was created.
             * @example 2024-01-15T12:00:00Z
             */
            timestamp: string;
            /**
             * Format: byte
             * @description Base64-encoded previous Merkle root for chaining.
             * @example cHJldmlvdXMgcm9vdA==
             */
            prevRoot?: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the request chain tip.
             * @example cmVxdWVzdCB0aXA=
             */
            requestChainTipHash: string;
            /**
             * Format: int64
             * @description Sequence of the request chain tip.
             * @example 100
             */
            requestChainTipSequence: number;
            /** @description Chain tips for all devices in this tree. */
            deviceChainTips: components["schemas"]["DeviceChainTip"][];
            /**
             * Format: byte
             * @description Base64-encoded Merkle root hash.
             * @example bWVya2xlIHJvb3Q=
             */
            merkleRoot: string;
            /** @description Proof data for tree reconstruction. */
            merkleProofData?: components["schemas"]["MerkleProof"];
            /**
             * Format: date-time
             * @description Timestamp when webhook was sent to customer.
             * @example 2024-01-15T12:00:01Z
             */
            customerWebhookSentAt?: string;
            /**
             * Format: int64
             * @description Total entries included in this tree.
             * @example 1234
             */
            totalEntryCount?: number;
        };
        /** @description Entry in the request chain tracking signing request lifecycle. */
        RequestChainEntry: {
            /**
             * @description Unique identifier for this entry.
             * @example entry_req123
             */
            entryId: string;
            /**
             * @description Organization ID for this entry.
             * @example org_xyz789
             */
            orgId: string;
            /**
             * Format: int64
             * @description Sequence number in the request chain.
             * @example 100
             */
            sequence: number;
            /**
             * Format: date-time
             * @description Timestamp when the entry was created.
             * @example 2024-01-15T12:00:00Z
             */
            timestamp: string;
            /**
             * Format: byte
             * @description Base64-encoded SHA256 hash of the entry.
             * @example ZW50cnkgaGFzaA==
             */
            entryHash: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the previous entry.
             * @example cHJldmlvdXMgaGFzaA==
             */
            prevHash?: string;
            /** @description Type of request event recorded. */
            entryType: components["schemas"]["AuditEntryType"];
            /**
             * @description ID of the signing request.
             * @example req_xyz789
             */
            requestId?: string;
            /**
             * @description ID of the requester.
             * @example rqr_abc123
             */
            requesterId?: string;
            /** @description HTTP context from the requester. */
            requesterContext?: components["schemas"]["RequesterContext"];
            /**
             * @description Lowercase hex-encoded public key of the key used for signing.
             * @example a1b2c3d4e5f6...
             */
            signingPublicKeyHex?: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the encrypted payload.
             * @example ZW5jcnlwdGVkIGhhc2g=
             */
            encryptedPayloadHash?: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the plaintext.
             * @example cGxhaW50ZXh0IGhhc2g=
             */
            plaintextHash?: string;
            /**
             * Format: date-time
             * @description When the request expired.
             * @example 2024-01-15T12:05:00Z
             */
            expiresAt?: string;
            /**
             * Format: byte
             * @description Base64-encoded hash linking to request creation entry.
             * @example cmVxdWVzdCBlbnRyeQ==
             */
            requestEntryHash?: string;
            /** @description Final outcome of the request. */
            outcome?: components["schemas"]["AuditOutcome"];
            /**
             * @description Device that responded first (for resolution entries).
             * @example dev_abc123
             */
            winningDeviceId?: string;
            /**
             * Format: byte
             * @description Base64-encoded hash of the winning device entry.
             * @example d2lubmluZyBoYXNo
             */
            winningDeviceEntryHash?: string;
        };
        /** @description Sanitized HTTP context from the signing requester. */
        RequesterContext: {
            /**
             * @description IP address of the requester client.
             * @example 192.168.1.100
             */
            clientIp?: string;
            /**
             * @description User-Agent header from the request.
             * @example AckAgent CLI/1.0.0
             */
            userAgent?: string;
            /**
             * @description Origin header for web requests.
             * @example https://app.example.com
             */
            origin?: string;
        };
        /** @description Details of a verification failure in the audit chain. */
        VerificationError: {
            /**
             * @description Entry ID where the error occurred.
             * @example entry_abc123
             */
            entryId?: string;
            /**
             * Format: int64
             * @description Sequence number of the problematic entry.
             * @example 42
             */
            sequence?: number;
            /**
             * @description Type of verification failure.
             * @example signature_invalid
             */
            errorType: string;
            /**
             * @description Human-readable error description.
             * @example Device signature does not match entry hash
             */
            description: string;
        };
        /** @description Result of verifying an audit chain's integrity. */
        VerificationResult: {
            /**
             * @description Whether the chain passed all verification checks.
             * @example true
             */
            valid: boolean;
            /**
             * Format: int64
             * @description Number of entries that were verified.
             * @example 1234
             */
            entriesCount: number;
            /** @description List of verification errors if invalid. */
            errors?: components["schemas"]["VerificationError"][];
            /**
             * @description Non-fatal issues found during verification.
             * @example [
             *       "Gap detected between entries 42 and 44"
             *     ]
             */
            warnings?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
