/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Health check
         */
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Readiness check - includes database connectivity check
         */
        get: operations["HealthReady_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get authentication challenge
         * @description Get authentication challenge - returns a challenge for signing key authentication
         */
        get: operations["AuthChallenge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/cors/origins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get allowed CORS origins
         * @description Get allowed CORS origins
         */
        get: operations["AuthCorsOrigins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's signing keys
         * @description Get user's signing keys
         */
        get: operations["AuthKeys_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a signing key
         * @description Delete a signing key
         */
        delete: operations["AuthKeyById_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info
         * @description Get current user info
         */
        get: operations["AuthMe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register new user with auth key
         * @description Register new user with auth key
         */
        post: operations["AuthRegister_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/relogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-login with existing auth key
         * @description Re-login with existing auth key - authenticate using a previously registered P-256 auth key
         */
        post: operations["AuthReLogin_relogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approver-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create approver session
         * @description Create approver session
         */
        post: operations["ApproverSessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approver-sessions/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim approver session
         * @description Claim approver session - existing device claims an approver session after scanning the QR code
         */
        post: operations["ApproverSessionClaim_claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approver-sessions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject SAS
         * @description Reject SAS - existing device rejects the SAS (mismatch or user declined)
         */
        post: operations["ApproverSessionReject_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approver-sessions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll approver session status
         * @description Poll approver session status
         */
        get: operations["ApproverSessionStatus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approver-sessions/{id}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tokens after verification
         * @description Get tokens after verification - new device fetches OAuth tokens after SAS verification is complete
         */
        get: operations["ApproverSessionTokens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approver-sessions/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify SAS match
         * @description Verify SAS match - existing device confirms the SAS displayed on new device matches
         */
        post: operations["ApproverSessionVerify_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvers/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link approver device to account
         * @description Link approver device to account - links an iOS/Android device to the authenticated user's account
         */
        post: operations["ApproversLink_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvers/{approverId}/attestation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get approver attestation
         * @description Get approver attestation
         */
        get: operations["ApproverAttestation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attest/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check attestation rate limit
         * @description Check attestation rate limit - check if attestation is allowed for the requester
         */
        get: operations["AttestCheck_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create connection
         * @description Create connection
         */
        post: operations["Connections_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requester-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create requester session
         * @description Create requester session
         */
        post: operations["RequesterSessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requester-sessions/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim requester session
         * @description Claim requester session - iOS device claims a requester session after scanning the QR code
         */
        post: operations["RequesterSessionClaim_claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requester-sessions/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject SAS
         * @description Reject SAS - iOS device rejects the SAS (mismatch or user declined)
         */
        post: operations["RequesterSessionReject_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requester-sessions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll requester session status
         * @description Poll requester session status
         */
        get: operations["RequesterSessionStatus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requester-sessions/{id}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tokens after verification
         * @description Get tokens after verification - CLI fetches OAuth tokens after SAS verification is complete
         */
        get: operations["RequesterSessionTokens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requester-sessions/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify SAS match
         * @description Verify SAS match - iOS device confirms the SAS displayed on CLI matches
         */
        post: operations["RequesterSessionVerify_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create requester
         * @description Create requester - creates a new requester registration for a user
         */
        post: operations["Requesters_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requesters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get requester
         * @description Get requester
         */
        get: operations["RequesterById_get"];
        put?: never;
        post?: never;
        /**
         * Delete requester
         * @description Delete requester
         */
        delete: operations["RequesterById_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requesters/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke requester
         * @description Revoke requester
         */
        post: operations["RequesterRevoke_revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/approver-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get approver signing keys
         * @description Get approver signing keys - returns P-256 public keys for all user's approver devices (for SAS computation)
         */
        get: operations["UserApproverKeys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/approver-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending approver sessions
         * @description List pending approver sessions - existing devices poll this to see pending device link sessions
         */
        get: operations["UserApproverSessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/approvers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's approver devices
         * @description List user's approver devices
         */
        get: operations["UserApprovers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/approvers/{approverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update approver device
         * @description Update approver device - update device info (APNs token, device type, etc.)
         */
        put: operations["UserApproverById_update"];
        post?: never;
        /**
         * Remove approver device
         * @description Remove approver device
         */
        delete: operations["UserApproverById_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/login-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List login history
         * @description List recent login attempts for the user, including pending and completed sessions
         */
        get: operations["UserLoginHistory_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/requester-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending requester sessions
         * @description List pending requester sessions - iOS devices poll this to see pending requester sessions for the user
         */
        get: operations["UserRequesterSessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/requesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user's requesters
         * @description List user's requesters
         */
        get: operations["UserRequesters_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll a BBS+ anonymous attestation credential
         * @description Enrolls a new BBS+ credential with pseudonym support for a device.
         *     The device provides a blind commitment (with ZK proof) over its nym secret.
         *     The auth service verifies the device's attestation and binding signature,
         *     then requests a blind signature from the credential-issuer service.
         */
        post: operations["Credentials_enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a BBS+ anonymous attestation credential
         * @description Refreshes an expiring credential. The device provides a new blind commitment
         *     (with ZK proof). The auth service revokes the old credential and issues a new one.
         */
        post: operations["Credentials_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get issuer public keys
         * @description Returns issuer public keys for BBS+ credential verification.
         *     Proxies to the credential-issuer service. No authentication required.
         */
        get: operations["Credentials_getPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Health check response */
        HealthResponse: {
            status: string;
        };
        /** @description CORS origins response */
        CorsOriginsResponse: {
            origins: string[];
        };
        /**
         * @description Session status values
         * @enum {string}
         */
        SessionStatus: "pending" | "claimed" | "verified" | "rejected" | "expired";
        /**
         * @description Requester status values
         * @enum {string}
         */
        RequesterStatus: "active" | "revoked";
        /** @description Approver device info */
        ApproverInfo: {
            /** @description Approver device UUID */
            approverId?: string;
            /** @description Lowercase hex-encoded P-256 auth public key (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            authPublicKeyHex?: string;
            deviceName?: string;
            deviceType?: string;
            /** @description Lowercase hex-encoded P-256 ECDH key for E2E encryption (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256), hardware-backed, no biometric) */
            encryptionPublicKeyHex?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUsedAt?: string;
            /** @description Full attestation data for client-side verification */
            attestation?: components["schemas"]["AttestationData"];
        };
        /** @description Approver key info for E2E encryption */
        ApproverKeyDetails: {
            /** @description Approver device UUID */
            approverId?: string;
            /** @description Lowercase hex-encoded P-256 auth public key (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            authPublicKeyHex?: string;
            /** @description Lowercase hex-encoded P-256 ECDH public key for E2E encryption (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256), no biometric) */
            encryptionPublicKeyHex?: string;
        };
        /** @description Approver attestation key info */
        ApproverKeyInfo: {
            /** @description Approver device UUID */
            approverId?: string;
            /** @description Lowercase hex-encoded P-256 auth public key (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            authPublicKeyHex?: string;
            /** @description Lowercase hex-encoded attestation key's public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            attestationPublicKeyHex?: string;
            attestationType?: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            deviceName?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description Approver keys response */
        ApproverKeysResponse: {
            keys?: components["schemas"]["ApproverKeyDetails"][];
        };
        /** @description Approver device link request */
        ApproverLinkRequest: {
            /** @description Device name for display */
            deviceName?: string;
            deviceType: components["schemas"]["AckAgent.Common.ApproverDeviceType"];
            /**
             * @description Lowercase hex-encoded P-256 ECDH public key for E2E encryption (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256), no biometric)
             * @example 0200a3b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2
             */
            encryptionPublicKeyHex: string;
            /**
             * @description Lowercase hex-encoded P-256 ECDSA auth public key (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256), hardware-backed)
             * @example 02b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2
             */
            authPublicKeyHex: string;
            /** @description APNs token for push notifications (iOS) */
            apnsToken?: string;
            attestationType?: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            /**
             * Format: byte
             * @description Apple CBOR attestation object (for attestation key)
             */
            attestationObject?: string;
            /**
             * Format: byte
             * @description Assertion from attestation key binding auth key
             */
            authKeyBindingAssertion?: string;
            /**
             * Format: byte
             * @description Challenge used for auth key binding
             */
            authKeyBindingChallenge?: string;
            /**
             * Format: byte
             * @description Assertion from attestation key binding encryption key
             */
            encryptionKeyBindingAssertion?: string;
            /**
             * Format: byte
             * @description Challenge used for encryption key binding
             */
            encryptionKeyBindingChallenge?: string;
            /** @description FCM token for push notifications (Android) */
            fcmToken?: string;
            /** @description DER-encoded certificate chain (Android Key Attestation) */
            androidAttestationChain?: string[];
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds when attestation was generated
             */
            attestationTimestamp?: number;
            /**
             * @description Lowercase hex-encoded attestation key's public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256))
             * @example 02a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2
             */
            attestationPublicKeyHex?: string;
            /** @description Google Play Integrity token (Android only, base64-encoded opaque token from IntegrityManager) */
            playIntegrityToken?: string;
            /**
             * Format: byte
             * @description Nonce used for Play Integrity token (SHA256(publicKey || challenge), base64)
             */
            playIntegrityNonce?: string;
        };
        /** @description Approver device link response */
        ApproverLinkResponse: {
            /** @description User ID (UUID) */
            userId?: string;
            /** @description Approver device UUID that was registered */
            approverId?: string;
            /** @description Whether this is a new user account */
            isNewUser?: boolean;
        };
        /** @description Approver session info for list */
        ApproverSessionInfo: {
            /** @description Session ID */
            id: string;
            deviceName: string;
            /**
             * Format: byte
             * @description New device's P-256 ephemeral key for session E2E encryption (33 bytes, base64)
             */
            sessionEncryptionKey: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description Attest check response */
        AttestCheckResponse: {
            allowed?: boolean;
            /** @description Current rate limit capacity */
            capacity?: number;
            /** @description Milliseconds until next attempt is allowed */
            retryAfterMs?: number;
            reason?: string;
        };
        /** @description Attestation data proving a response came from a genuine device. In "identified" mode, includes full device identity. In "anonymous" mode (future), proves genuine device without revealing identity. */
        AttestationData: {
            /**
             * @description Attestation mode for device enrollment. Always "identified" for auth service device attestation (includes full device identity).
             * @enum {string}
             */
            mode: "identified";
            /** @description Human-readable device name for display */
            deviceName?: string;
            deviceType: components["schemas"]["AckAgent.Common.ApproverDeviceType"];
            attestationType: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            /** @description Lowercase hex-encoded attestation key's public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)). Present in "identified" mode. */
            attestationPublicKeyHex?: string;
            /** @description Lowercase hex-encoded P-256 ECDH public key for E2E encryption (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            encryptionPublicKeyHex?: string;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds when attestation was generated
             */
            timestamp: number;
            /** @description DER-encoded certificate chain for verification (array of base64 strings). Present in "identified" mode. */
            certificateChain?: string[];
            /**
             * Format: byte
             * @description Direct attestation of the response by the attestation key. Base64-encoded.
             */
            responseAssertion?: string;
            /** @description Google Play Integrity verdict (Android only, populated after server-side verification) */
            playIntegrityVerdict?: {
                /** @description Device integrity level (MEETS_DEVICE_INTEGRITY, MEETS_BASIC_INTEGRITY, MEETS_STRONG_INTEGRITY, MEETS_VIRTUAL_INTEGRITY) */
                deviceRecognitionVerdict?: string;
                /** @description App integrity (PLAY_RECOGNIZED, UNRECOGNIZED_VERSION, UNEVALUATED) */
                appRecognitionVerdict?: string;
                /** @description Account licensing (LICENSED, UNLICENSED, UNEVALUATED) */
                accountLicensingVerdict?: string;
                /**
                 * Format: date-time
                 * @description When the verdict was verified by the backend
                 */
                verifiedAt?: string;
            };
        };
        /** @description Challenge response for re-login */
        ChallengeResponse: {
            /** @description Server-generated challenge ID for re-login (UUID) */
            challengeId: string;
            /** @description Random challenge bytes (base64) */
            challenge: string;
            /**
             * Format: int32
             * @description Seconds until challenge expires
             */
            expiresIn: number;
        };
        /** @description Claim approver session request */
        ClaimApproverSessionRequest: {
            /**
             * Format: byte
             * @description New device's P-256 ephemeral key from QR code for SAS verification
             */
            sessionEncryptionKey?: string;
        };
        /** @description Claim approver session response */
        ClaimApproverSessionResponse: {
            /** @description Session ID for tracking */
            sessionId: string;
            /** @description New device's display name */
            deviceName: string;
            /**
             * Format: byte
             * @description New device's P-256 ephemeral key for session E2E encryption (33 bytes, base64)
             */
            sessionEncryptionKey: string;
            /** @description Lowercase hex-encoded P-256 ECDSA auth public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            authPublicKeyHex?: string;
            attestationType?: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            /**
             * Format: byte
             * @description Apple CBOR attestation object for auth key
             */
            authAttestationObject?: string;
            /**
             * Format: byte
             * @description App Attest assertion binding the auth key to the session key
             */
            keyBindingAssertion?: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Source IP of the new device for display during SAS verification */
            sourceIp?: string;
        };
        /** @description Claim requester session request */
        ClaimRequesterSessionRequest: {
            /** @description Lowercase hex-encoded requester P-256 public key from QR code (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            requesterPublicKeyHex?: string;
        };
        /** @description Claim requester session response */
        ClaimRequesterSessionResponse: {
            /** @description Session ID for tracking */
            sessionId: string;
            /** @description Requester display name */
            requesterName: string;
            /** @description Lowercase hex-encoded requester P-256 ECDH public key for E2E encryption (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            requesterPublicKeyHex: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Source IP of the requester for display during SAS verification */
            sourceIp?: string;
        };
        /** @description Create approver session request */
        CreateApproverSessionRequest: {
            deviceName: string;
            /**
             * Format: byte
             * @description P-256 ephemeral key for session E2E encryption (33 bytes, base64)
             */
            sessionEncryptionKey: string;
            /** @description Lowercase hex-encoded P-256 ECDSA auth public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            authPublicKeyHex?: string;
            attestationType?: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            /**
             * Format: byte
             * @description Apple CBOR attestation object for auth key
             */
            authAttestationObject?: string;
            /**
             * Format: byte
             * @description App Attest assertion binding the auth key to the session key (challenge = SHA256(sessionEncryptionKey))
             */
            keyBindingAssertion?: string;
            /**
             * Format: int32
             * @default 300
             */
            expiresIn: number;
        };
        /** @description Create approver session response */
        CreateApproverSessionResponse: {
            sessionId: string;
            status: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Secret required to fetch tokens - prevents session fixation attacks */
            tokenClaimSecret: string;
        };
        /** @description Create connection request */
        CreateConnectionRequest: {
            requesterId: string;
            requesterName: string;
            /** @description Lowercase hex-encoded requester P-256 public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            requesterPublicKeyHex: string;
            /**
             * Format: int32
             * @default 300
             */
            expiresIn: number;
        };
        /** @description Create connection response */
        CreateConnectionResponse: {
            /** @description Session ID for tracking this connection */
            sessionId: string;
            /** @description Current session status */
            status: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Full attestation data for all approver devices - requester should verify these */
            approvers: components["schemas"]["AttestationData"][];
        };
        /** @description Create requester request */
        CreateRequesterRequest: {
            requesterId: string;
            requesterName: string;
            requesterUrl?: string;
            /** @description Lowercase hex-encoded requester P-256 public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            requesterPublicKeyHex: string;
            userId: string;
        };
        /** @description Create requester session request */
        CreateRequesterSessionRequest: {
            requesterId?: string;
            /** @default CLI */
            requesterName: string;
            /** @description Lowercase hex-encoded requester P-256 ECDH public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            requesterPublicKeyHex: string;
            /**
             * Format: int32
             * @default 300
             */
            expiresIn: number;
        };
        /** @description Create requester session response */
        CreateRequesterSessionResponse: {
            sessionId: string;
            status: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Secret required to fetch tokens - prevents session fixation attacks */
            tokenClaimSecret: string;
        };
        /** @description Get approver session status response */
        GetApproverSessionStatusResponse: {
            status?: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            expiresAt?: string;
            userId?: string;
            /** @description Existing approver public keys for SAS computation */
            approverKeys?: components["schemas"]["ApproverKeyDetails"][];
        };
        /** @description Get approver session tokens response */
        GetApproverSessionTokensResponse: {
            accessToken: string;
            refreshToken?: string;
            /** Format: int32 */
            expiresIn: number;
            tokenType: string;
            userId: string;
            approverKeys?: components["schemas"]["ApproverKeyDetails"][];
        };
        /** @description Get attestation response */
        GetAttestationResponse: {
            /** @description Full attestation data for client-side verification */
            attestation?: components["schemas"]["AttestationData"];
            /** @description Whether the device has valid attestation */
            attested?: boolean;
        };
        /** @description Get keys response */
        GetKeysResponse: {
            keys?: components["schemas"]["ApproverKeyInfo"][];
        };
        /** @description Get me response */
        GetMeResponse: {
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description Get requester session status response */
        GetRequesterSessionStatusResponse: {
            status?: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            expiresAt?: string;
            userId?: string;
            requesterId?: string;
            /** @description UUID of the approver handling this session (set when claimed/verified) */
            claimingApproverId?: string;
            /** @description Approver public keys for SAS computation */
            approverKeys?: components["schemas"]["ApproverKeyDetails"][];
        };
        /** @description Get requester session tokens response */
        GetRequesterSessionTokensResponse: {
            accessToken: string;
            refreshToken?: string;
            /** Format: int32 */
            expiresIn: number;
            tokenType: string;
            userId: string;
            requesterId?: string;
            approverKeys?: components["schemas"]["ApproverKeyDetails"][];
        };
        /** @description Internal approver token information */
        InternalApproverToken: {
            /** @description Approver device UUID */
            approverId: string;
            approverType: string;
            apnsToken?: string;
            fcmToken?: string;
        };
        /** @description Internal approver tokens response */
        InternalApproverTokensResponse: {
            approvers: components["schemas"]["InternalApproverToken"][];
        };
        /** @description Internal device token */
        InternalDeviceToken: {
            /** @description Approver device UUID */
            approverId?: string;
            /** @description Lowercase hex-encoded P-256 auth public key (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            authPublicKeyHex?: string;
            /** @description Device type */
            deviceType?: string;
            /** @description APNs device token (hex-encoded) */
            apnsToken?: string;
            /** @description FCM registration token */
            fcmToken?: string;
        };
        /** @description Internal device tokens response */
        InternalDeviceTokensResponse: {
            devices?: components["schemas"]["InternalDeviceToken"][];
        };
        /** @description Response confirming all user sessions have been revoked. */
        InternalSessionRevokeResponse: {
            /** @description Status message confirming session revocation. */
            message?: string;
        };
        /** @description Internal requester response */
        InternalRequesterResponse: {
            id?: string;
            userId?: string;
            requesterId?: string;
            requesterName?: string;
            /** @description Lowercase hex-encoded requester P-256 public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            requesterPublicKeyHex?: string;
            status?: components["schemas"]["RequesterStatus"];
        };
        /** @description Internal attestation key info response */
        InternalAttestationKeyInfoResponse: {
            /** @description Approver device UUID */
            approverId: string;
            /** @description Lowercase hex-encoded P-256 auth public key (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            authPublicKeyHex: string;
            /** @description Lowercase hex-encoded attestation key's public key (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            attestationPublicKeyHex: string;
            attestationType: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            userId: string;
        };
        /** @description Internal validate requester response */
        InternalValidateRequesterResponse: {
            /** @description Whether the requester is valid for the specified user */
            valid?: boolean;
        };
        /** @description List approvers response */
        ListApproversResponse: {
            approvers?: components["schemas"]["ApproverInfo"][];
        };
        /** @description List login history response */
        ListLoginHistoryResponse: {
            entries: components["schemas"]["LoginHistoryEntry"][];
        };
        /** @description List requesters response */
        ListRequestersResponse: {
            requesters?: components["schemas"]["RequesterResponse"][];
        };
        /** @description List user approver sessions response */
        ListUserApproverSessionsResponse: {
            sessions?: components["schemas"]["ApproverSessionInfo"][];
        };
        /** @description List user requester sessions response */
        ListUserRequesterSessionsResponse: {
            sessions?: components["schemas"]["RequesterSessionInfo"][];
        };
        /** @description Login history entry */
        LoginHistoryEntry: {
            /** @description Session ID */
            id: string;
            /** @description Requester ID */
            requesterId?: string;
            /** @description Requester name (CLI name or web app name) */
            requesterName?: string;
            status: components["schemas"]["SessionStatus"];
            /** @description Source IP address */
            sourceIp?: string;
            /**
             * Format: date-time
             * @description When the login was initiated
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the session expires
             */
            expiresAt?: string;
        };
        /** @description Re-login request - authenticate using a previously registered P-256 auth key */
        ReLoginRequest: {
            /**
             * @description Lowercase hex-encoded P-256 auth public key (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256))
             * @example 02b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2
             */
            authPublicKeyHex: string;
            attestationType: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            /** @description Auth key binding assertion proving ownership (base64) */
            authKeyBindingAssertion: string;
            /** @description Challenge ID from /api/auth/challenge */
            challengeId: string;
            /** @description Device name for display */
            deviceName: string;
            /** @description APNs token for push notifications (iOS) */
            apnsToken?: string;
        };
        /** @description Re-login response */
        ReLoginResponse: {
            userId?: string;
            accessToken?: string;
            refreshToken?: string;
            /** Format: int32 */
            expiresIn?: number;
        };
        /** @description Register request */
        RegisterRequest: {
            /**
             * @description Lowercase hex-encoded P-256 auth public key for auth service authentication (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256))
             * @example 02b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2
             */
            authPublicKeyHex: string;
            /** @description App Attest attestation object for auth key (base64) */
            authAttestationObject?: string;
            /** @description Key binding assertion proving auth key ownership (base64) */
            authKeyBindingAssertion?: string;
            /** @description Challenge for auth key binding (base64) */
            authKeyBindingChallenge?: string;
            attestationType: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            deviceName: string;
            /**
             * @description Lowercase hex-encoded P-256 ECDH encryption public key, compressed format (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256))
             * @example 0200a3b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2
             */
            encryptionPublicKeyHex?: string;
        };
        /** @description Register response */
        RegisterResponse: {
            userId?: string;
            accessToken?: string;
            refreshToken?: string;
            /** Format: int32 */
            expiresIn?: number;
        };
        /** @description Requester response */
        RequesterResponse: {
            id?: string;
            requesterId?: string;
            requesterName?: string;
            requesterUrl?: string;
            userId?: string;
            status?: components["schemas"]["RequesterStatus"];
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description Requester session info for list */
        RequesterSessionInfo: {
            /** @description Session ID */
            id: string;
            requesterName: string;
            /** @description Lowercase hex-encoded requester P-256 ECDH public key for SAS computation (66 hex chars, 33 bytes: 0x02/0x03 || X (compressed P-256)) */
            requesterPublicKeyHex: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description Update approver request */
        UpdateApproverRequest: {
            deviceName?: string;
            deviceType?: string;
            apnsToken?: string;
            /** @enum {string} */
            apnsEnvironment?: "development" | "production";
            fcmToken?: string;
            /** @description Lowercase hex-encoded P-256 ECDH public key for E2E encryption (66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256), no biometric) */
            encryptionPublicKeyHex?: string;
            /**
             * Format: byte
             * @description Assertion from attestation key binding encryption key
             */
            encryptionKeyBindingAssertion?: string;
        };
        /** @description Verify approver session request */
        VerifyApproverSessionRequest: {
            /** @description User ID from OIDC token */
            userId?: string;
        };
        /** @description Verify approver session response */
        VerifyApproverSessionResponse: {
            success?: boolean;
        };
        /** @description Verify requester session request */
        VerifyRequesterSessionRequest: {
            /** @description User ID from OIDC token */
            userId?: string;
        };
        /** @description Verify requester session response */
        VerifyRequesterSessionResponse: {
            /** @description Verification status */
            status: string;
            /** @description ID of the created requester pairing */
            pairingId: string;
        };
        /** @description Request to enroll a BBS+ anonymous attestation credential. */
        EnrollCredentialRequest: {
            /**
             * Format: byte
             * @description Base64-encoded blind commitment with ZK proof from bbs_commit_with_nym(). Proves the holder knows their nym secret without revealing it.
             */
            commitmentWithProof: string;
            /**
             * Format: byte
             * @description Base64-encoded P-256 ECDSA signature over SHA256(commitmentWithProof), proving the attested device controls the commitment.
             */
            bindingSignature: string;
            /** @description Approver device UUID. */
            deviceId: string;
        };
        /** @description Request to refresh a BBS+ anonymous attestation credential. */
        RefreshCredentialRequest: {
            /**
             * Format: byte
             * @description Base64-encoded blind commitment with ZK proof for the new credential.
             */
            commitmentWithProof: string;
            /**
             * Format: byte
             * @description Base64-encoded P-256 ECDSA signature over SHA256(commitmentWithProof), proving the attested device controls the commitment.
             */
            bindingSignature: string;
            /** @description Approver device UUID. */
            deviceId: string;
        };
        /** @description Response containing the blind signature, issuer nym entropy, and signer messages. The holder must call bbs_verify_blind_sign_with_nym() to verify the signature and extract the combined nym secret. */
        EnrollCredentialResponse: {
            /**
             * Format: byte
             * @description Base64-encoded 80-byte BBS+ blind signature.
             */
            blindSignature: string;
            /**
             * Format: byte
             * @description Base64-encoded 32-byte issuer nym entropy. Combined with the holder's nym secret via bbs_verify_blind_sign_with_nym() to derive the combined nym secret used for pseudonym generation.
             */
            signerNymEntropy: string;
            /**
             * Format: byte
             * @description Base64-encoded 96-byte BLS12-381 G2 issuer public key.
             */
            issuerPublicKey: string;
            /** @description Unique identifier of the issuer key that signed this credential. */
            issuerPublicKeyId: string;
            /** @description Base64-encoded signer messages in signing order: [attestationType, deviceType, issuedAt, expiresAt]. The holder needs these exact values for blind signature verification and later proof generation. */
            messages: string[];
            /**
             * Format: int64
             * @description Credential expiry as Unix epoch seconds.
             */
            expiresAt: number;
        };
        /** @description Issuer public key information for BBS+ credential verification. */
        IssuerPublicKeyInfo: {
            /** @description Unique key identifier. */
            id: string;
            /**
             * Format: byte
             * @description Base64-encoded BLS12-381 G2 public key (96 bytes).
             */
            publicKey: string;
            /** @description Signing algorithm identifier. */
            algorithm: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            rotatedAt?: string | null;
        };
        ErrorResponse: {
            /** @description Human-readable error message */
            error: string;
        };
        /**
         * @description Combined platform and security level for attestation.
         * @enum {string}
         */
        "AckAgent.Common.AttestationSecurityType": "ios_secure_enclave" | "android_tee" | "android_strongbox" | "software" | "play_integrity";
        /**
         * @description Device platform type.
         * @enum {string}
         */
        "AckAgent.Common.ApproverDeviceType": "ios" | "android";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    HealthReady_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthChallenge_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
        };
    };
    AuthCorsOrigins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorsOriginsResponse"];
                };
            };
        };
    };
    AuthKeys_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetKeysResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthKeyById_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier for the signing key */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthMe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMeResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthRegister_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthReLogin_relogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReLoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReLoginResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproverSessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApproverSessionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateApproverSessionResponse"];
                };
            };
        };
    };
    ApproverSessionClaim_claim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Approver session identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimApproverSessionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimApproverSessionResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproverSessionReject_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Approver session identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproverSessionStatus_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Approver session identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApproverSessionStatusResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproverSessionTokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Approver session identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApproverSessionTokensResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproverSessionVerify_verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Approver session identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyApproverSessionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyApproverSessionResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproversLink_link: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproverLinkRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproverLinkResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credential service unavailable. The credential-issuer service is down or has no active signing key. Retry after a short delay. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApproverAttestation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Approver device UUID */
                approverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAttestationResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AttestCheck_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttestCheckResponse"];
                };
            };
        };
    };
    Connections_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateConnectionResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterSessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequesterSessionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRequesterSessionResponse"];
                };
            };
        };
    };
    RequesterSessionClaim_claim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequesterSessionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimRequesterSessionResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterSessionReject_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterSessionStatus_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequesterSessionStatusResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterSessionTokens_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRequesterSessionTokensResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterSessionVerify_verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequesterSessionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyRequesterSessionResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Requesters_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequesterRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequesterResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterById_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequesterResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterById_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequesterRevoke_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserApproverKeys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproverKeysResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserApproverSessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUserApproverSessionsResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserApprovers_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListApproversResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserApproverById_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
                /** @description Approver device UUID */
                approverId: string;
            };
            cookie?: never;
        };
        /** @description Request payload */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApproverRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserApproverById_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
                /** @description Approver device UUID */
                approverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserLoginHistory_list: {
        parameters: {
            query?: {
                /** @description Maximum number of results to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListLoginHistoryResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserRequesterSessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUserRequesterSessionsResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserRequesters_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRequestersResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Credentials_enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollCredentialRequest"];
            };
        };
        responses: {
            /** @description Credential enrolled successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollCredentialResponse"];
                };
            };
            /** @description Invalid request (bad fields, binding signature invalid). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Active credential already exists for this device. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Credentials_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshCredentialRequest"];
            };
        };
        responses: {
            /** @description Credential refreshed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollCredentialResponse"];
                };
            };
            /** @description Invalid request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device attestation or authorization policy forbids credential refresh. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No active credential found to refresh. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Credentials_getPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issuer public keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuerPublicKeyInfo"][];
                };
            };
        };
    };
}
