/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/organizations/{orgId}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get encrypted blob
         * @description Retrieves the current encrypted blob for the organization. Returns the encrypted data along with per-device wrapped keys and version information. Requires organization membership.
         */
        get: operations["Blob_get"];
        /**
         * Update encrypted blob
         * @description Updates the encrypted blob using optimistic locking. The If-Match header must contain the current ETag to prevent concurrent modification conflicts.
         */
        put: operations["Blob_update"];
        /**
         * Create encrypted blob
         * @description Creates a new encrypted blob for the organization. Only succeeds if no blob currently exists. Requires device attestation and org membership.
         */
        post: operations["Blob_create"];
        /**
         * Delete encrypted blob
         * @description Permanently deletes the encrypted blob for the organization. Requires device attestation and org membership. This action cannot be undone.
         */
        delete: operations["Blob_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/blob/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List blob history
         * @description Returns a list of previous blob versions for the organization. Each entry contains the version number and creation timestamp. Use the version number to retrieve or restore a specific version.
         */
        get: operations["BlobHistory_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/blob/history/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get history version
         * @description Retrieves a specific historical version of the encrypted blob. Can be used to review previous data before restoring.
         */
        get: operations["BlobHistoryVersion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{orgId}/blob/restore/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore blob from history
         * @description Restores the blob to a previous version from history. Creates a new version with the historical data. Requires device attestation and org membership.
         */
        post: operations["BlobRestore_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current health status of the blob service. Used by load balancers and monitoring systems.
         */
        get: operations["Health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Returns the readiness status including database connectivity. Used by orchestrators to determine if the service can accept traffic.
         */
        get: operations["HealthReady_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request payload for creating or updating an encrypted blob with per-device wrapped keys. */
        BlobRequest: {
            /**
             * Format: byte
             * @description Base64-encoded encrypted blob data using ChaCha20-Poly1305.
             * @example ZW5jcnlwdGVkIGJsb2IgZGF0YQ==
             */
            encryptedBlob: string;
            /**
             * Format: byte
             * @description Base64-encoded 12-byte nonce used for blob encryption.
             * @example bm9uY2UxMjM0NTY3ODkwMTI=
             */
            blobNonce: string;
            /**
             * @description Array of per-device wrapped encryption keys.
             * @example [
             *       {
             *         "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
             *         "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
             *         "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
             *         "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
             *       }
             *     ]
             */
            wrappedKeys: components["schemas"]["WrappedKey"][];
            /**
             * @description Lowercase hex-encoded auth public key of the device for attestation. 66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256).
             * @example 02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2
             */
            authPublicKeyHex?: string;
            /**
             * Format: byte
             * @description Base64-encoded device assertion for write authorization.
             * @example YXNzZXJ0aW9uIGRhdGE=
             */
            assertion?: string;
        };
        /** @description Response containing the encrypted blob, wrapped keys, and version metadata. */
        BlobResponse: {
            /**
             * Format: byte
             * @description Base64-encoded encrypted blob data.
             * @example ZW5jcnlwdGVkIGJsb2IgZGF0YQ==
             */
            encryptedBlob: string;
            /**
             * Format: byte
             * @description Base64-encoded nonce used for blob encryption.
             * @example bm9uY2UxMjM0NTY3ODkwMTI=
             */
            blobNonce: string;
            /**
             * @description Array of per-device wrapped encryption keys.
             * @example [
             *       {
             *         "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
             *         "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
             *         "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
             *         "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
             *       }
             *     ]
             */
            wrappedKeys: components["schemas"]["WrappedKey"][];
            /**
             * Format: int32
             * @description Monotonically increasing version number for optimistic locking.
             * @example 5
             */
            version: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the last update.
             * @example 2024-01-15T12:00:00Z
             */
            updatedAt: string;
        };
        /** @description Detailed response for a specific historical version of the blob. */
        HistoryDetailResponse: {
            /**
             * Format: byte
             * @description Base64-encoded encrypted blob data from this historical version.
             * @example aGlzdG9yaWNhbCBibG9iIGRhdGE=
             */
            encryptedBlob: string;
            /**
             * Format: byte
             * @description Base64-encoded nonce from this historical version.
             * @example aGlzdG9yeSBub25jZQ==
             */
            blobNonce: string;
            /**
             * @description Per-device wrapped keys from this historical version.
             * @example [
             *       {
             *         "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
             *         "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
             *         "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
             *         "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
             *       }
             *     ]
             */
            wrappedKeys: components["schemas"]["WrappedKey"][];
            /**
             * Format: int32
             * @description Version number of this historical snapshot.
             * @example 3
             */
            version: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when this version was created.
             * @example 2024-01-13T09:15:00Z
             */
            createdAt: string;
        };
        /** @description Summary entry for a blob version in the history list. */
        HistoryEntry: {
            /**
             * Format: int32
             * @description Version number that can be used to retrieve or restore this snapshot.
             * @example 5
             */
            version: number;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp when this version was created.
             * @example 2024-01-15T12:00:00Z
             */
            createdAt: string;
        };
        /** @description Response containing the list of available historical versions. */
        HistoryListResponse: {
            /**
             * @description List of historical blob versions, ordered by version number descending.
             * @example [
             *       {
             *         "version": 5,
             *         "createdAt": "2024-01-15T12:00:00Z"
             *       },
             *       {
             *         "version": 4,
             *         "createdAt": "2024-01-14T18:30:00Z"
             *       }
             *     ]
             */
            history: components["schemas"]["HistoryEntry"][];
        };
        /** @description Per-device wrapped encryption key for multi-device blob access. */
        WrappedKey: {
            /**
             * @description Lowercase hex-encoded P-256 ECDH public key of the device that can unwrap this key. 66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256).
             * @example 02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2
             */
            encryptionPublicKeyHex: string;
            /**
             * @description Lowercase hex-encoded ephemeral P-256 public key used for key wrapping. 66 hex chars for P-256, 33 bytes: 0x02/0x03 || X (compressed P-256).
             * @example 02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5
             */
            ephemeralPublicHex: string;
            /**
             * Format: byte
             * @description Base64-encoded wrapped symmetric key encrypted with ChaCha20-Poly1305.
             * @example d3JhcHBlZCBrZXkgZGF0YQ==
             */
            wrappedKey: string;
            /**
             * Format: byte
             * @description Base64-encoded 12-byte nonce used for key wrapping.
             * @example d3JhcHBlZCBrZXkgbm9uY2U=
             */
            wrappedKeyNonce: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Blob_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encrypted blob retrieved successfully. The ETag header contains the current version for optimistic locking. */
            200: {
                headers: {
                    /** @description Current version ETag for use in subsequent updates. */
                    etag: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "encryptedBlob": "ZW5jcnlwdGVkIGJsb2IgZGF0YQ==",
                     *       "blobNonce": "bm9uY2UxMjM0NTY3ODkwMTI=",
                     *       "wrappedKeys": [
                     *         {
                     *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                     *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                     *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                     *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                     *         }
                     *       ],
                     *       "version": 5,
                     *       "updatedAt": "2024-01-15T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["BlobResponse"];
                };
            };
            /** @description Missing or invalid authentication token. Obtain a valid token from the login service. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No blob exists for this organization. Use POST to create an initial blob. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Blob_update: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Current version ETag from the last GET or update response. Required for optimistic locking.
                 * @example "v5"
                 */
                "if-match": string;
            };
            path: {
                /** @description Organization ID */
                orgId: string;
            };
            cookie?: never;
        };
        /** @description Updated encrypted blob data with attestation information. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "encryptedBlob": "dXBkYXRlZCBlbmNyeXB0ZWQgYmxvYg==",
                 *       "blobNonce": "bmV3IG5vbmNlIHZhbHVl",
                 *       "wrappedKeys": [
                 *         {
                 *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                 *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                 *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                 *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                 *         }
                 *       ],
                 *       "authPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                 *       "assertion": "YXNzZXJ0aW9uIGRhdGE="
                 *     }
                 */
                "application/json": components["schemas"]["BlobRequest"];
            };
        };
        responses: {
            /** @description Encrypted blob updated successfully. The ETag header contains the new version. */
            200: {
                headers: {
                    /** @description New version ETag for use in subsequent updates. */
                    etag: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "encryptedBlob": "dXBkYXRlZCBlbmNyeXB0ZWQgYmxvYg==",
                     *       "blobNonce": "bmV3IG5vbmNlIHZhbHVl",
                     *       "wrappedKeys": [
                     *         {
                     *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                     *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                     *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                     *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                     *         }
                     *       ],
                     *       "version": 6,
                     *       "updatedAt": "2024-01-15T12:05:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["BlobResponse"];
                };
            };
            /** @description Invalid request payload. Verify all required fields are present. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid authentication token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device attestation failed or device is not authorized for write operations. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No blob exists for this organization. Use POST to create one first. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ETag mismatch - the blob was modified by another device. Fetch the latest version and retry. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Blob_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                orgId: string;
            };
            cookie?: never;
        };
        /** @description Encrypted blob data with per-device wrapped keys and attestation. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "encryptedBlob": "ZW5jcnlwdGVkIGJsb2IgZGF0YQ==",
                 *       "blobNonce": "bm9uY2UxMjM0NTY3ODkwMTI=",
                 *       "wrappedKeys": [
                 *         {
                 *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                 *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                 *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                 *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                 *         }
                 *       ],
                 *       "authPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                 *       "assertion": "YXNzZXJ0aW9uIGRhdGE="
                 *     }
                 */
                "application/json": components["schemas"]["BlobRequest"];
            };
        };
        responses: {
            /** @description Encrypted blob created successfully. The ETag header contains the initial version. */
            201: {
                headers: {
                    /** @description Initial version ETag for use in subsequent updates. */
                    etag: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "encryptedBlob": "ZW5jcnlwdGVkIGJsb2IgZGF0YQ==",
                     *       "blobNonce": "bm9uY2UxMjM0NTY3ODkwMTI=",
                     *       "wrappedKeys": [
                     *         {
                     *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                     *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                     *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                     *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                     *         }
                     *       ],
                     *       "version": 1,
                     *       "updatedAt": "2024-01-15T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["BlobResponse"];
                };
            };
            /** @description Invalid request payload. Verify all required fields are present and correctly encoded. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid authentication token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device attestation failed or device is not authorized for write operations. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A blob already exists for this organization. Use PUT to update the existing blob. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Blob_delete: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Lowercase hex-encoded auth public key of the device for attestation verification.
                 * @example a1b2c3d4e5f6...
                 */
                "x-device-auth-key": string;
                /**
                 * @description Base64-encoded device assertion proving control of the signing key.
                 * @example YXNzZXJ0aW9uIGRhdGE=
                 */
                "x-assertion": string;
            };
            path: {
                /** @description Organization ID */
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blob deleted successfully. No content returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid authentication token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device attestation failed or device is not authorized for delete operations. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlobHistory_list: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of versions to return. Defaults to 20, maximum is 100.
                 * @example 10
                 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Organization ID */
                orgId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description History list retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "history": [
                     *         {
                     *           "version": 5,
                     *           "createdAt": "2024-01-15T12:00:00Z"
                     *         },
                     *         {
                     *           "version": 4,
                     *           "createdAt": "2024-01-14T18:30:00Z"
                     *         },
                     *         {
                     *           "version": 3,
                     *           "createdAt": "2024-01-13T09:15:00Z"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["HistoryListResponse"];
                };
            };
            /** @description Missing or invalid authentication token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlobHistoryVersion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization ID */
                orgId: string;
                /**
                 * @description Version number to retrieve.
                 * @example 3
                 */
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical version retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "encryptedBlob": "aGlzdG9yaWNhbCBibG9iIGRhdGE=",
                     *       "blobNonce": "aGlzdG9yeSBub25jZQ==",
                     *       "wrappedKeys": [
                     *         {
                     *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                     *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                     *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                     *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                     *         }
                     *       ],
                     *       "version": 3,
                     *       "createdAt": "2024-01-13T09:15:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["HistoryDetailResponse"];
                };
            };
            /** @description Missing or invalid authentication token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Specified version does not exist in the history. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BlobRestore_restore: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Lowercase hex-encoded auth public key of the device for attestation verification.
                 * @example a1b2c3d4e5f6...
                 */
                "x-device-auth-key": string;
                /**
                 * @description Base64-encoded device assertion proving control of the signing key.
                 * @example YXNzZXJ0aW9uIGRhdGE=
                 */
                "x-assertion": string;
            };
            path: {
                /** @description Organization ID */
                orgId: string;
                /**
                 * @description Version number to restore from.
                 * @example 3
                 */
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blob restored successfully to the current version. */
            200: {
                headers: {
                    /** @description New version ETag after restoration. */
                    etag: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "encryptedBlob": "cmVzdG9yZWQgYmxvYiBkYXRh",
                     *       "blobNonce": "cmVzdG9yZWQgbm9uY2U=",
                     *       "wrappedKeys": [
                     *         {
                     *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                     *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                     *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                     *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                     *         }
                     *       ],
                     *       "version": 7,
                     *       "updatedAt": "2024-01-15T12:10:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["BlobResponse"];
                };
            };
            /** @description Blob created from historical version (when no current blob exists). */
            201: {
                headers: {
                    /** @description Initial version ETag after restoration. */
                    etag: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "encryptedBlob": "cmVzdG9yZWQgYmxvYiBkYXRh",
                     *       "blobNonce": "cmVzdG9yZWQgbm9uY2U=",
                     *       "wrappedKeys": [
                     *         {
                     *           "encryptionPublicKeyHex": "02a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
                     *           "ephemeralPublicHex": "02f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5",
                     *           "wrappedKey": "d3JhcHBlZCBrZXkgZGF0YQ==",
                     *           "wrappedKeyNonce": "d3JhcHBlZCBrZXkgbm9uY2U="
                     *         }
                     *       ],
                     *       "version": 1,
                     *       "updatedAt": "2024-01-15T12:10:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["BlobResponse"];
                };
            };
            /** @description Missing or invalid authentication token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Device attestation failed or device is not authorized for restore operations. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Specified version does not exist in the history. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy and accepting requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    HealthReady_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready and all dependencies are healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
            /** @description Service is not ready. Database or other dependencies may be unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
