/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["Health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/public-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get issuer public keys
         * @description Returns all active and recently-rotated issuer public keys. Verifiers
         *     use these to validate BBS+ credential proofs. No authentication required.
         */
        get: operations["Credentials_getPublicKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credentials/verify-proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a captcha proof
         * @description Public endpoint for third-party websites to verify a captcha proof
         *     envelope generated by the NaughtBot SDK. The proof is a base64url-encoded
         *     BBS+ selective disclosure proof with pseudonym binding. Returns the
         *     attestation details on success.
         */
        post: operations["Credentials_verifyCaptchaProof"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        IssuerPublicKey: {
            /** @description Unique key identifier */
            id: string;
            /**
             * Format: byte
             * @description Base64-encoded BLS12-381 G2 public key (96 bytes)
             */
            publicKey: string;
            /**
             * @description Signing algorithm identifier
             * @example BBS-BLS12381-SHA256
             */
            algorithm: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            rotatedAt?: string | null;
        };
        VerifyCaptchaProofRequest: {
            /** @description Base64url-encoded proof envelope from the NaughtBot SDK */
            proof: string;
            /** @description Session nonce used during proof generation */
            nonce: string;
            /** @description Domain of the requesting website */
            domain: string;
        };
        VerifyCaptchaProofResponse: {
            /** @description Whether the proof is valid */
            valid: boolean;
            attestation?: components["schemas"]["CaptchaAttestation"];
            /** @description Human-readable error message (present when valid is false) */
            error?: string;
        };
        CaptchaAttestation: {
            /**
             * @description Type of attestation (e.g. biometric, device)
             * @example biometric
             */
            attestationType: string;
            /**
             * @description Device platform (e.g. ios, android)
             * @example ios
             */
            deviceType: string;
            /**
             * Format: date-time
             * @description When the attestation expires
             */
            expiresAt: string;
        };
        ErrorResponse: {
            /** @description Human-readable error message */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    Credentials_getPublicKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of issuer public keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuerPublicKey"][];
                };
            };
        };
    };
    Credentials_verifyCaptchaProof: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCaptchaProofRequest"];
            };
        };
        responses: {
            /** @description Proof is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCaptchaProofResponse"];
                };
            };
            /** @description Invalid request (malformed proof, missing fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Proof verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCaptchaProofResponse"];
                };
            };
        };
    };
}
