/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Combined platform and security level for attestation.
         * @enum {string}
         */
        "AckAgent.Common.AttestationSecurityType": "ios_secure_enclave" | "android_tee" | "android_strongbox" | "software" | "play_integrity";
        /**
         * @description Device platform type.
         * @enum {string}
         */
        "AckAgent.Common.ApproverDeviceType": "ios" | "android";
        /** @description Anonymous attestation envelope using W3C Data Integrity (`bbs-2023`). Proves the response came from a genuine device with a valid credential from a known issuer without revealing device identity. Travels inside the encrypted response blob so the relay stays completely blind. */
        "AckAgent.Common.AnonymousAttestation": {
            /** @description JSON-LD context array for VC/Data Integrity semantics. */
            "@context": string[];
            /** @description Presentation type array (includes VerifiablePresentation). */
            type: string[];
            proof: components["schemas"]["AckAgent.Common.DataIntegrityProof"];
            ackagentAnonymousAttestation: components["schemas"]["AckAgent.Common.AnonymousAttestationPayload"];
        };
        /**
         * @description Purpose of the key being enrolled.
         * @example ssh
         * @enum {string}
         */
        "AckAgent.Common.KeyPurpose": "ssh" | "gpg" | "age";
        /**
         * @description Error codes for signing failures (1=rejected, 2=timeout, 3=key_not_found, 4=invalid_payload, 5=attestation_failed, 6=internal_error).
         * @example 1
         * @enum {integer}
         */
        "AckAgent.Common.SigningErrorCode": 1 | 2 | 3 | 4 | 5 | 6;
        /**
         * @description Type of signing or approval request.
         * @example gpg_sign
         * @enum {string}
         */
        "AckAgent.Common.TransactionType": "ssh_auth" | "ssh_sign" | "gpg_sign" | "gpg_decrypt" | "age_unwrap" | "ecdh_derive" | "custom" | "claude_approval" | "claude_question" | "enroll" | "device_login" | "web" | "pam_auth" | "captcha";
        /** @description Schema for displaying approval requests to users. */
        GenericDisplaySchema: {
            /**
             * @description Main title for the approval screen.
             * @example Sign Git Commit
             */
            title: string;
            /**
             * @description Shorter title for history list view.
             * @example Git Commit
             */
            historyTitle?: string;
            /**
             * @description Subtitle with additional context.
             * @example user/repo on main
             */
            subtitle?: string;
            /**
             * @description SF Symbol name for iOS.
             * @example signature
             */
            icon?: string;
            /** @description Fields to display in the approval UI. */
            fields: components["schemas"]["DisplayField"][];
        };
        /** @description A field to display in the approval UI. */
        DisplayField: {
            /**
             * @description Label for the field.
             * @example Repository
             */
            label: string;
            /**
             * @description Value to display.
             * @example github.com/user/repo
             */
            value: string;
            /**
             * @description Render value in monospace font.
             * @default false
             * @example true
             */
            monospace: boolean;
            /**
             * @description Field can be expanded to show more content.
             * @default false
             * @example false
             */
            expandable: boolean;
            /**
             * @description Render value as multiline text.
             * @default false
             * @example false
             */
            multiline: boolean;
            /**
             * @description Value contains sensitive information.
             * @default false
             * @example false
             */
            sensitive: boolean;
            /**
             * @description SF Symbol name for iOS UI.
             * @example server.rack
             */
            icon?: string;
        };
        /** @description Entry in a process tree. */
        ProcessEntry: {
            /**
             * Format: int32
             * @description Process ID.
             * @example 12345
             */
            pid: number;
            /**
             * @description Username running the process.
             * @example root
             */
            username: string;
            /**
             * @description Command line of the process.
             * @example /usr/bin/sudo apt update
             */
            command: string;
        };
        /** @description Information about the requesting system and process ancestry. */
        SourceInfo: {
            /**
             * @description Source machine hostname.
             * @example laptop.local
             */
            hostname?: string;
            /**
             * @description Local/private IP address.
             * @example 192.168.1.50
             */
            localIp?: string;
            /**
             * @description User running the process.
             * @example admin
             */
            username?: string;
            /**
             * @description Command line of the current process.
             * @example git commit -S -m "message"
             */
            command?: string;
            /** @description Full process tree from current process up to init. */
            processChain?: components["schemas"]["ProcessEntry"][];
        };
        /** @description Base structure for all encrypted payloads. */
        BasePayload: {
            /** @description Type of request. */
            type: components["schemas"]["AckAgent.Common.TransactionType"];
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. Present on CLI-originated requests. */
            sourceInfo?: components["schemas"]["SourceInfo"];
        };
        /** @description Generic signature response for SSH and custom requests. */
        SignatureResponse: {
            /**
             * Format: byte
             * @description Base64url-encoded signature.
             * @example c2lnbmF0dXJl
             */
            signature?: string;
            /**
             * @description Request correlation ID.
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            requestId?: string;
            /**
             * @description Approval status.
             * @example approved
             * @enum {string}
             */
            status?: "approved" | "rejected";
            /**
             * Format: int32
             * @description SSH replay protection counter.
             * @example 1
             */
            counter?: number;
            /** @description Error code if signing failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description SSH authentication request payload. */
        SshAuthPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example ssh_auth
             * @enum {string}
             */
            type: "ssh_auth";
            /**
             * Format: byte
             * @description Base64-encoded raw SSH challenge data (preimage). The approver constructs the SSH signature input from this preimage.
             * @example c3NoIGNoYWxsZW5nZQ==
             */
            rawData: string;
            /**
             * @description Key ID to use for signing.
             * @example key_abc123
             */
            keyId?: string;
            /**
             * @description SSH application identifier (e.g., "ssh:").
             * @example ssh:
             */
            application?: string;
            /**
             * Format: int32
             * @description SSH SK flags bitmask (default 0x01 = user presence required).
             * @default 1
             * @example 1
             */
            flags: number;
            /**
             * @description iOS key identifier for key selection.
             * @example key_abc123
             */
            iosKeyId?: string;
        };
        /** @description SSH signing request payload. */
        SshSignPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example ssh_sign
             * @enum {string}
             */
            type: "ssh_sign";
            /**
             * Format: byte
             * @description Base64-encoded raw data to sign (preimage). The approver constructs the SSH signature input from this preimage.
             * @example ZGF0YSB0byBzaWdu
             */
            rawData: string;
            /**
             * @description Key ID to use for signing.
             * @example key_abc123
             */
            keyId?: string;
            /**
             * @description SSH application identifier (e.g., "ssh:").
             * @example ssh:
             */
            application?: string;
            /**
             * Format: int32
             * @description SSH SK flags bitmask (default 0x01 = user presence required).
             * @default 1
             * @example 1
             */
            flags: number;
            /**
             * @description iOS key identifier for key selection.
             * @example key_abc123
             */
            iosKeyId?: string;
        };
        /** @description GPG signing request payload. */
        GpgSignPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @description Request type identifier.
             * @example gpg_sign
             * @enum {string}
             */
            type: "gpg_sign";
            /**
             * Format: byte
             * @description Base64-encoded raw data to sign (preimage). The approver builds the OpenPGP hash input from this preimage and signs the resulting digest.
             * @example cmF3IGRhdGE=
             */
            rawData: string;
        };
        /** @description GPG signature response with armored signature. */
        GpgSignatureResponse: {
            /**
             * @description ASCII-armored OpenPGP signature.
             * @example -----BEGIN PGP SIGNATURE-----...
             */
            armoredSignature?: string;
            /** @description Error code if signing failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description GPG decryption request payload. */
        GpgDecryptPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example gpg_decrypt
             * @enum {string}
             */
            type: "gpg_decrypt";
            /**
             * Format: byte
             * @description Base64-encoded encrypted data to decrypt.
             * @example ZW5jcnlwdGVkIGRhdGE=
             */
            encryptedData: string;
            /** @description Public Key Encrypted Session Key data for decryption. */
            pkesk?: components["schemas"]["PkeskData"];
        };
        /** @description GPG decryption response with session key. */
        GpgDecryptResponse: {
            /**
             * Format: byte
             * @description Base64-encoded unwrapped session key.
             * @example c2Vzc2lvbiBrZXk=
             */
            sessionKey?: string;
            /**
             * Format: int32
             * @description OpenPGP symmetric algorithm ID.
             * @example 9
             */
            algorithm?: number;
            /** @description Error code if decryption failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description Public Key Encrypted Session Key data from OpenPGP PKESK packet. */
        PkeskData: {
            /**
             * Format: int32
             * @description PKESK packet version (typically 3).
             * @example 3
             */
            version: number;
            /**
             * Format: byte
             * @description Base64-encoded 8-byte recipient key ID.
             * @example a2V5X2lkMTIz
             */
            keyId: string;
            /**
             * Format: int32
             * @description OpenPGP public key algorithm (18 = ECDH).
             * @example 18
             */
            algorithm: number;
            /**
             * Format: byte
             * @description Base64-encoded ephemeral ECDH public point (33 bytes compressed).
             * @example ZXBoZW1lcmFsX3BvaW50
             */
            ephemeralPoint: string;
            /**
             * Format: byte
             * @description Base64-encoded AES-wrapped session key.
             * @example d3JhcHBlZF9rZXk=
             */
            wrappedKey: string;
        };
        /** @description Request to unwrap an age-encrypted file key. */
        AgeUnwrapPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example age_unwrap
             * @enum {string}
             */
            type: "age_unwrap";
            /**
             * @description Lowercase hex-encoded sender's ephemeral X25519 public key (64 hex chars for 32-byte key).
             * @example a1b2c3d4e5f6...
             */
            ephemeralPublicHex: string;
            /**
             * Format: byte
             * @description Base64-encoded wrapped file key for decryption.
             * @example d3JhcHBlZCBmaWxlIGtleQ==
             */
            wrappedFileKey: string;
            /**
             * @description Lowercase hex-encoded recipient's X25519 public key (64 hex chars for 32-byte key).
             * @example b2c3d4e5f6a1...
             */
            recipientPublicHex: string;
        };
        /** @description Response containing the unwrapped file key or error. */
        AgeUnwrapResponse: {
            /**
             * Format: byte
             * @description Base64-encoded unwrapped file key for decryption.
             * @example ZmlsZSBrZXk=
             */
            fileKey?: string;
            /** @description Error code if the operation failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description ECDH key derivation request payload. */
        EcdhDerivePayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example ecdh_derive
             * @enum {string}
             */
            type: "ecdh_derive";
            /**
             * @description Lowercase hex-encoded peer's public key for ECDH (66 hex chars for P-256 33-byte compressed key).
             * @example 02a1b2c3d4e5f6...
             */
            peerPublicHex: string;
            /** @description Optional KDF parameters for key derivation. */
            kdf?: components["schemas"]["EcdhKdfParams"];
        };
        /** @description ECDH key derivation response. */
        EcdhDeriveResponse: {
            /**
             * Format: byte
             * @description Base64-encoded derived shared secret.
             * @example c2hhcmVkIHNlY3JldA==
             */
            sharedSecret?: string;
            /** @description Error code if the operation failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description Parameters for ECDH key derivation function. */
        EcdhKdfParams: {
            /**
             * @description KDF algorithm name.
             * @example HKDF-SHA256
             */
            algorithm?: string;
            /**
             * Format: int32
             * @description Desired output key length in bytes.
             * @example 32
             */
            keyLength?: number;
            /**
             * Format: byte
             * @description Base64-encoded KDF info parameter.
             * @example aW5mbw==
             */
            info?: string;
        };
        /** @description Claude Code tool approval request payload. */
        ClaudeApprovalPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example claude_approval
             * @enum {string}
             */
            type: "claude_approval";
            /**
             * @description Name of the Claude Code tool (e.g., 'Bash', 'Write', 'Edit').
             * @example Bash
             */
            toolName: string;
            /**
             * @description Formatted tool input for display to the user.
             * @example rm -rf /tmp/test
             */
            toolInputFormatted: string;
            /**
             * @description Whether the user can modify the input before approval.
             * @example true
             */
            allowsModification?: boolean;
            /**
             * @description Claude Code session identifier.
             * @example session_abc123
             */
            sessionId?: string;
            /**
             * Format: byte
             * @description Base64-encoded canonical JSON of the approval context (session_id, tool_name, tool_input, timestamp). The approver computes SHA-256 of this preimage and signs the resulting digest.
             * @example eyJzZXNzaW9uX2lkIjoic2Vzc2lvbl9hYmMxMjMifQ==
             */
            contextPreimage?: string;
            /**
             * @description Title for the approval prompt.
             * @example Allow command?
             */
            actionTitle?: string;
            /**
             * @description Description of what the action will do.
             * @example Execute shell command in your terminal
             */
            actionDescription?: string;
        };
        /** @description Claude Code approval response with decision and signature. */
        ClaudeApprovalResponse: {
            /**
             * @description User's approval decision.
             * @example allow
             * @enum {string}
             */
            decision: "allow" | "allow_always" | "deny";
            /**
             * Format: byte
             * @description Base64-encoded ECDSA signature over the SHA-256 digest of contextPreimage.
             * @example Y29udGV4dCBzaWduYXR1cmU=
             */
            contextSignature: string;
            /** @description Modified input if the user edited it before approval. */
            updatedInput?: {
                [key: string]: unknown;
            };
            /** @description Rule to remember for allow_always decisions. */
            rememberRule?: components["schemas"]["RememberRule"];
            /** @description Error code if the operation failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description A question for the user to answer via the mobile app. */
        ClaudeQuestion: {
            /**
             * @description Unique identifier for this question.
             * @example q_abc123
             */
            id: string;
            /**
             * @description Question text to display to the user.
             * @example Which database should I use?
             */
            question: string;
            /**
             * @description Header label for the question.
             * @example Database Choice
             */
            header?: string;
            /** @description Available answer options. */
            options: components["schemas"]["ClaudeQuestionOption"][];
            /**
             * @description Whether an answer is required.
             * @example true
             */
            required?: boolean;
            /**
             * @description Whether multiple options can be selected.
             * @example false
             */
            multiSelect?: boolean;
        };
        /** @description A selectable option for a Claude question. */
        ClaudeQuestionOption: {
            /**
             * @description Unique identifier for this option.
             * @example opt_postgres
             */
            id: string;
            /**
             * @description Display label for the option.
             * @example PostgreSQL
             */
            label: string;
            /**
             * @description Additional description for the option.
             * @example Recommended for production workloads
             */
            description?: string;
        };
        /** @description Claude Code question request payload. */
        ClaudeQuestionPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example claude_question
             * @enum {string}
             */
            type: "claude_question";
            /** @description Array of questions to ask the user. */
            questions: components["schemas"]["ClaudeQuestion"][];
            /**
             * @description Claude Code session identifier.
             * @example session_abc123
             */
            sessionId?: string;
        };
        /** @description Claude Code question response with signed answers. */
        ClaudeQuestionResponse: {
            /**
             * Format: byte
             * @description Base64-encoded JSON of the user's answers.
             * @example eyJxX2FiYzEyMyI6Im9wdF9wb3N0Z3JlcyJ9
             */
            answersBytes?: string;
            /**
             * Format: byte
             * @description Base64-encoded ECDSA signature over the SHA-256 digest of answersBytes. The approver computes the digest from the canonical JSON answers before signing.
             * @example YW5zd2VycyBzaWduYXR1cmU=
             */
            answersSignature?: string;
            /** @description Error code if the operation failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description Rule for remembering allow_always decisions. */
        RememberRule: {
            /**
             * @description Tool name to remember.
             * @example Bash
             */
            tool: string;
            /**
             * @description Pattern to match for auto-approval.
             * @example npm test
             */
            pattern?: string;
        };
        /** @description Key enrollment request payload. */
        EnrollPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example enroll
             * @enum {string}
             */
            type: "enroll";
            /** @description Purpose of the key (ssh, gpg, age). */
            purpose: components["schemas"]["AckAgent.Common.KeyPurpose"];
            /**
             * @description Human-readable label for the key.
             * @example Work Laptop SSH Key
             */
            label?: string;
            /**
             * @description Key algorithm to use.
             * @example ed25519
             */
            algorithm?: string;
            /**
             * @description Include self-certification signature for GPG export.
             * @example true
             */
            includeCertification?: boolean;
        };
        /** @description Key enrollment response with public key or error. */
        EnrollResponse: {
            /**
             * @description Enrollment result.
             * @example approved
             * @enum {string}
             */
            status: "approved" | "rejected";
            /**
             * @description Key UUID (for GPG keys).
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id?: string;
            /**
             * @description Lowercase hex-encoded public key (66 hex chars for P-256 33-byte key, or 64 hex chars for Ed25519 32-byte key).
             * @example 02a1b2c3d4e5f6...
             */
            publicKeyHex?: string;
            /**
             * @description iOS Secure Enclave key identifier.
             * @example key_abc123
             */
            iosKeyId?: string;
            /**
             * @description Key algorithm used.
             * @example ed25519
             */
            algorithm?: string;
            /**
             * @description GPG fingerprint for GPG keys.
             * @example ABCD1234EFGH5678
             */
            fingerprint?: string;
            /**
             * Format: int64
             * @description Unix timestamp when the key was created.
             * @example 1705320000
             */
            keyCreationTimestamp?: number;
            /**
             * Format: byte
             * @description Base64-encoded self-certification signature.
             * @example dXNlciBpZCBzaWc=
             */
            userIdSignature?: string;
            /**
             * Format: byte
             * @description Base64-encoded subkey binding signature.
             * @example c3Via2V5IHNpZw==
             */
            subkeySignature?: string;
            /** @description Lowercase hex-encoded ECDH encryption subkey public key (66 hex chars for P-256 33-byte compressed key). */
            encryptionPublicKeyHex?: string;
            /** @description 40-character hex fingerprint of the ECDH encryption subkey. */
            encryptionFingerprint?: string;
            /** @description Attestation proof that the key was created on attested device hardware. */
            attestation?: components["schemas"]["AckAgent.Common.KeyMetadataAttestation"];
            /** @description Error code if enrollment failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the enrollment
             */
            errorMessage?: string;
        };
        /** @description PAM authentication request payload. */
        PamAuthPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example pam_auth
             * @enum {string}
             */
            type: "pam_auth";
            /**
             * @description Local Unix username being authenticated.
             * @example admin
             */
            localUsername: string;
            /**
             * @description AckAgent user email for verification.
             * @example user@example.com
             */
            ackagentUser: string;
            /**
             * @description PAM service name (e.g., sudo, sshd).
             * @example sudo
             */
            pamService: string;
            /**
             * @description Remote host IP for SSH sessions.
             * @example 192.168.1.100
             */
            remoteHost?: string;
            /**
             * @description TTY device.
             * @example /dev/pts/0
             */
            tty?: string;
            /**
             * @description OS version of the host.
             * @example Ubuntu 22.04
             */
            osVersion?: string;
            /**
             * @description SSH client info from environment.
             * @example 192.168.1.50 54321 22
             */
            sshClient?: string;
            /**
             * @description SSH connection info from environment.
             * @example 192.168.1.50 54321 192.168.1.100 22
             */
            sshConnection?: string;
            /**
             * @description SSH original command if any.
             * @example git-upload-pack '/repo.git'
             */
            sshOriginalCommand?: string;
            /**
             * @description Whether SSH_AUTH_SOCK is present.
             * @example true
             */
            sshAuthSockPresent?: boolean;
            /**
             * @description User who invoked sudo.
             * @example developer
             */
            sudoUser?: string;
            /**
             * @description Command being run via sudo.
             * @example /usr/bin/apt update
             */
            sudoCommand?: string;
            /**
             * @description Challenge code for offline verification.
             * @example ABC123
             */
            challenge?: string;
            /**
             * Format: int64
             * @description Unix timestamp of the request.
             * @example 1705320000
             */
            timestamp: number;
        };
        /** @description PAM authentication response. */
        PamAuthResponse: {
            /**
             * @description Approval decision.
             * @example approved
             * @enum {string}
             */
            status: "approved" | "rejected";
            /**
             * @description Response code for offline verification.
             * @example XYZ789
             */
            responseCode?: string;
            /**
             * Format: byte
             * @description Base64-encoded device signature.
             * @example c2lnbmF0dXJl
             */
            signature?: string;
            /**
             * Format: int64
             * @description Unix timestamp of the response.
             * @example 1705320001
             */
            timestamp?: number;
            /**
             * @description Lowercase hex-encoded auth public key of the responding device (66 hex chars for P-256 33-byte key, or 64 hex chars for Ed25519 32-byte key).
             * @example a1b2c3d4e5f6...
             */
            authPublicKeyHex?: string;
            /** @description Error code if authentication failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description Web approval request payload. */
        WebPayload: {
            /** @description Display metadata for the approval UI. */
            display?: components["schemas"]["GenericDisplaySchema"];
            /**
             * @example web
             * @enum {string}
             */
            type: "web";
            /**
             * @description Title for the approval request.
             * @example Confirm Payment
             */
            title: string;
            /**
             * @description Description of what is being approved.
             * @example Authorize payment of $100 to Example Inc.
             */
            description?: string;
            /**
             * @description Plaintext content to approve.
             * @example Payment authorization for $100
             */
            plaintext: string;
            /** @description Browser metadata from the web request. */
            browserMetadata: components["schemas"]["BrowserMetadata"];
        };
        /** @description Web approval response with signature. */
        WebApprovalResponse: {
            /**
             * Format: byte
             * @description Base64-encoded ECDSA signature over the SHA-256 digest of the plaintext preimage.
             * @example c2lnbmF0dXJl
             */
            signature?: string;
            /**
             * @description SHA-256 digest of the plaintext preimage, computed by the approver (format: 'sha256:<hex>').
             * @example sha256:abc123...
             */
            plaintextHash?: string;
            /** @description Error code if approval failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User rejected the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device. Present for all approval responses. Inside the encrypted blob. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description Browser metadata captured for web approval requests. */
        BrowserMetadata: {
            /**
             * @description Full URL of the page initiating the request.
             * @example https://app.example.com/sign
             */
            url: string;
            /**
             * @description Origin of the page (protocol + host).
             * @example https://app.example.com
             */
            origin: string;
            /**
             * @description Title of the web page.
             * @example Sign Document - Example App
             */
            pageTitle?: string;
            /**
             * @description Browser user agent string.
             * @example Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
             */
            userAgent?: string;
            /**
             * @description Referrer URL if available.
             * @example https://app.example.com/documents
             */
            referrer?: string;
            /**
             * @description ISO 8601 timestamp when metadata was collected.
             * @example 2024-01-15T12:00:00Z
             */
            timestamp: string;
        };
        /** @description Captcha verification request payload. */
        CaptchaPayload: {
            /**
             * @example captcha
             * @enum {string}
             */
            type: "captcha";
            /**
             * @description Website domain requesting captcha verification.
             * @example example.com
             */
            domain: string;
            /**
             * @description Unique nonce for replay protection.
             * @example abc123def456
             */
            nonce: string;
            /**
             * Format: int64
             * @description Unix timestamp of request creation (milliseconds).
             * @example 1705320000000
             */
            timestamp: number;
        };
        /** @description Captcha verification response. */
        CaptchaResponse: {
            /**
             * @description Whether the user approved the captcha.
             * @example true
             */
            approved: boolean;
            /**
             * @description SHA-256 digest of the plaintext preimage, computed by the approver (format: 'sha256:<hex>').
             * @example sha256:abc123...
             */
            plaintextHash?: string;
            /** @description Error code if verification failed. */
            errorCode?: components["schemas"]["AckAgent.Common.SigningErrorCode"];
            /**
             * @description Human-readable error message.
             * @example User declined the request
             */
            errorMessage?: string;
            /** @description Anonymous attestation proving the response came from a genuine device with a valid credential. Present for all approval responses. Inside the encrypted blob so the relay stays blind. */
            attestation?: components["schemas"]["AckAgent.Common.AnonymousAttestation"];
        };
        /** @description Custom signing request with application-defined data. */
        CustomPayload: {
            /** @description Source system and process ancestry information. */
            sourceInfo?: components["schemas"]["SourceInfo"];
            /**
             * @example custom
             * @enum {string}
             */
            type: "custom";
            /**
             * Format: byte
             * @description Base64-encoded raw data to sign (preimage). The approver computes the SHA-256 digest and signs it.
             * @example Y3VzdG9tIGRhdGE=
             */
            rawData: string;
            /** @description Required display schema for custom payloads. */
            display: components["schemas"]["GenericDisplaySchema"];
        };
        /** @description Metadata extracted from encrypted payloads for display. */
        TransactionMetadata: {
            /**
             * @description SSH target hostname.
             * @example server.example.com
             */
            hostname?: string;
            /**
             * @description SSH username.
             * @example admin
             */
            username?: string;
            /**
             * Format: int32
             * @description SSH port.
             * @example 22
             */
            port?: number;
            /**
             * @description SSH command being executed.
             * @example ls -la
             */
            command?: string;
            /** @description Process chain for SSH operations. */
            processChain?: components["schemas"]["ProcessEntry"][];
            /**
             * @description Source machine hostname.
             * @example laptop.local
             */
            sourceHostname?: string;
            /**
             * @description Local IP address.
             * @example 192.168.1.50
             */
            localIp?: string;
            /**
             * @description File name for GPG operations.
             * @example document.pdf
             */
            fileName?: string;
            /**
             * @description Git commit message.
             * @example feat: add new feature
             */
            commitMessage?: string;
            /**
             * @description Recipient email for encryption.
             * @example recipient@example.com
             */
            recipientEmail?: string;
            /**
             * @description Whether this is a git commit signing.
             * @example true
             */
            isGitCommit?: boolean;
            /**
             * @description Git tree hash.
             * @example abc123def456
             */
            treeHash?: string;
            /**
             * @description Git parent commit hashes.
             * @example [
             *       "parent123"
             *     ]
             */
            parentHashes?: string[];
            /**
             * @description Git author name.
             * @example John Doe
             */
            authorName?: string;
            /**
             * @description Git author email.
             * @example john@example.com
             */
            authorEmail?: string;
            /**
             * Format: int64
             * @description Git author timestamp.
             * @example 1705320000
             */
            authorTimestamp?: number;
            /**
             * @description Git committer name.
             * @example John Doe
             */
            committerName?: string;
            /**
             * @description Git committer email.
             * @example john@example.com
             */
            committerEmail?: string;
            /**
             * Format: int64
             * @description Git committer timestamp.
             * @example 1705320000
             */
            committerTimestamp?: number;
            /**
             * @description Git branch name.
             * @example main
             */
            branch?: string;
            /**
             * @description Repository name.
             * @example user/repo
             */
            repoName?: string;
            /**
             * @description Full command line.
             * @example git commit -S -m "message"
             */
            commandLine?: string;
            /**
             * @description Type of operation.
             * @example sign
             */
            operationType?: string;
            /**
             * @description Input source description.
             * @example file
             */
            inputSource?: string;
            /**
             * @description Whether input is from stdin.
             * @example false
             */
            isStdin?: boolean;
            /**
             * Format: int32
             * @description Content size in bytes.
             * @example 1024
             */
            contentSize?: number;
            /**
             * @description Hash of the content.
             * @example sha256:abc123...
             */
            contentHash?: string;
            /**
             * @description Preview of the content.
             * @example First 100 characters...
             */
            contentPreview?: string;
            /**
             * @description Full content if small enough.
             * @example Full content here
             */
            contentFull?: string;
            /**
             * @description Sender key ID for encryption.
             * @example ABCD1234
             */
            senderKeyId?: string;
            /**
             * @description Recipient key ID.
             * @example EFGH5678
             */
            encryptedTo?: string;
            /**
             * Format: int32
             * @description Encrypted message size.
             * @example 2048
             */
            messageSize?: number;
            /**
             * @description Whether recipient is anonymous.
             * @example false
             */
            isAnonymous?: boolean;
            /**
             * @description Age file name.
             * @example secrets.age
             */
            ageFileName?: string;
            /**
             * Format: int64
             * @description Age file size.
             * @example 4096
             */
            ageFileSize?: number;
            /**
             * @description Lowercase hex-encoded age ephemeral X25519 public key (64 hex chars for 32-byte key).
             * @example a1b2c3d4e5f6...
             */
            ageEphemeralPublicHex?: string;
            /**
             * Format: byte
             * @description Base64-encoded age wrapped file key.
             * @example YWdlIHdyYXBwZWQ=
             */
            ageWrappedFileKey?: string;
            /**
             * @description Lowercase hex-encoded age recipient X25519 public key (64 hex chars for 32-byte key).
             * @example b2c3d4e5f6a1...
             */
            ageRecipientPublicHex?: string;
            /**
             * @description Action title for display.
             * @example Sign Document
             */
            actionTitle?: string;
            /**
             * @description Action description.
             * @example Sign this PDF document
             */
            actionDescription?: string;
            /**
             * @description Plaintext content.
             * @example Content to approve
             */
            plaintext?: string;
            /**
             * @description Hash of the plaintext.
             * @example sha256:xyz789...
             */
            plaintextHash?: string;
            /**
             * @description Content MIME type.
             * @example text/plain
             */
            contentType?: string;
            /**
             * @description Claude tool name.
             * @example Bash
             */
            toolName?: string;
            /**
             * @description Formatted tool input.
             * @example npm test
             */
            toolInputFormatted?: string;
            /**
             * @description Base64-encoded canonical JSON of the approval context preimage.
             * @example eyJzZXNzaW9uX2lkIjoic2Vzc2lvbl9hYmMxMjMifQ==
             */
            contextPreimage?: string;
            /**
             * @description Whether modification is allowed.
             * @example true
             */
            allowsModification?: boolean;
            /**
             * @description Claude session ID.
             * @example session_123
             */
            claudeSessionId?: string;
            /**
             * @description SAS verification words.
             * @example [
             *       "alpha",
             *       "bravo"
             *     ]
             */
            sasWords?: string[];
            /**
             * @description SAS verification emojis.
             * @example [
             *       "🔒",
             *       "✅"
             *     ]
             */
            sasEmojis?: string[];
            /**
             * @description Login session ID.
             * @example login_abc123
             */
            loginSessionId?: string;
            /**
             * @description Enrollment purpose.
             * @example ssh
             */
            purpose?: string;
            /**
             * @description Enrollment algorithm.
             * @example ed25519
             */
            algorithm?: string;
            /**
             * @description Key label.
             * @example Work Laptop
             */
            label?: string;
            /**
             * @description Additional key-value metadata.
             * @example {
             *       "custom_field": "custom_value"
             *     }
             */
            additionalInfo?: {
                [key: string]: string;
            };
        };
        /** @description Any valid request payload type. */
        RequestPayload: components["schemas"]["GpgSignPayload"] | components["schemas"]["SshAuthPayload"] | components["schemas"]["SshSignPayload"] | components["schemas"]["GpgDecryptPayload"] | components["schemas"]["AgeUnwrapPayload"] | components["schemas"]["EcdhDerivePayload"] | components["schemas"]["ClaudeApprovalPayload"] | components["schemas"]["ClaudeQuestionPayload"] | components["schemas"]["EnrollPayload"] | components["schemas"]["CustomPayload"] | components["schemas"]["WebPayload"] | components["schemas"]["PamAuthPayload"] | components["schemas"]["CaptchaPayload"];
        /** @description Any valid response payload type. */
        ResponsePayload: components["schemas"]["SignatureResponse"] | components["schemas"]["GpgSignatureResponse"] | components["schemas"]["GpgDecryptResponse"] | components["schemas"]["AgeUnwrapResponse"] | components["schemas"]["EcdhDeriveResponse"] | components["schemas"]["ClaudeApprovalResponse"] | components["schemas"]["ClaudeQuestionResponse"] | components["schemas"]["EnrollResponse"] | components["schemas"]["WebApprovalResponse"] | components["schemas"]["PamAuthResponse"] | components["schemas"]["CaptchaResponse"];
        /** @description W3C Data Integrity proof object for bbs-2023 presentations. */
        "AckAgent.Common.DataIntegrityProof": {
            /**
             * @description Data Integrity proof type.
             * @enum {string}
             */
            type: "DataIntegrityProof";
            /**
             * @description Data Integrity cryptosuite identifier.
             * @enum {string}
             */
            cryptosuite: "bbs-2023";
            /** @description Serialized BBS+ proof value. Canonical format is multibase base64url (prefix `u`), with URL-safe/base64 compatibility accepted during migration. */
            proofValue: string;
            /**
             * Format: date-time
             * @description Optional proof creation timestamp.
             */
            created?: string;
            /** @description Optional proof verification method identifier. */
            verificationMethod?: string;
            /** @description Optional proof purpose. */
            proofPurpose?: string;
        };
        /** @description Messages disclosed by the BBS+ selective disclosure proof. These are the only credential attributes visible to the verifier. */
        "AckAgent.Common.AnonymousAttestationRevealedMessages": {
            attestationType: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            deviceType: components["schemas"]["AckAgent.Common.ApproverDeviceType"];
            /**
             * Format: int64
             * @description Credential expiry as Unix epoch seconds.
             */
            expiresAt: number;
        };
        /** @description Optional scoped-linking metadata for cross-device experiments. */
        "AckAgent.Common.AnonymousAttestationScopedLinking": {
            /**
             * @description Scoped-linking mechanism identifier.
             * @enum {string}
             */
            mode: "pairwise_account_secret";
            /**
             * @description Linkability boundary taxonomy.
             * @enum {string}
             */
            scopeType: "request" | "relying_party" | "organization";
            /** @description Scope identifier (for example relying-party ID or organization ID). */
            scopeId: string;
            /** @description Opaque URL-safe pairwise linking handle. */
            linkHandle: string;
        };
        /** @description AckAgent-specific payload inside the W3C envelope. */
        "AckAgent.Common.AnonymousAttestationPayload": {
            /**
             * Format: byte
             * @description Scope-bound pseudonym (48 bytes compressed G1 point, base64). Deterministically derived from the holder's nym secret and the scope. Same secret + same scope = same pseudonym (enables replay detection). Different scopes produce unrelated pseudonyms (prevents cross-request correlation).
             */
            pseudonym: string;
            /** @description Scope used for pseudonym derivation (request ID). Per-request pseudonyms provide maximum privacy. */
            scope: string;
            /**
             * Format: byte
             * @description Presentation header bound to the proof (base64). Provides freshness binding to the specific request.
             */
            presentationHeader: string;
            revealedMessages: components["schemas"]["AckAgent.Common.AnonymousAttestationRevealedMessages"];
            /** @description Unique identifier of the issuer key that signed the prover's credential. Enables verifiers to look up the correct key for proof verification during key rotation. */
            issuerPublicKeyId: string;
            scopedLinking?: components["schemas"]["AckAgent.Common.AnonymousAttestationScopedLinking"];
        };
        /** @description Attestation proof that a key was created on attested device hardware. */
        "AckAgent.Common.KeyMetadataAttestation": {
            /** @description Lowercase hex-encoded public key being attested (66 hex chars for P-256 33-byte key, or 64 hex chars for Ed25519 32-byte key). */
            publicKeyHex: string;
            /**
             * Format: byte
             * @description App Attest assertion or software signature (base64)
             */
            assertion: string;
            attestationType: components["schemas"]["AckAgent.Common.AttestationSecurityType"];
            /**
             * Format: byte
             * @description Apple CBOR attestation object for hardware attestation (base64)
             */
            attestationObject?: string;
            /**
             * Format: byte
             * @description SHA256(id || publicKey || createdAt || deviceAuthPublicKey)
             */
            challenge: string;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds
             */
            attestationTimestamp: number;
            /** @description Lowercase hex-encoded attestation key's public key (66 hex chars for P-256 33-byte compressed key). */
            attestationPublicKeyHex?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
