// Package credentialissuer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package credentialissuer

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// CaptchaAttestation defines model for CaptchaAttestation.
type CaptchaAttestation struct {
	// AttestationType Type of attestation (e.g. biometric, device)
	AttestationType string `json:"attestationType"`

	// DeviceType Device platform (e.g. ios, android)
	DeviceType string `json:"deviceType"`

	// ExpiresAt When the attestation expires
	ExpiresAt time.Time `json:"expiresAt"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Human-readable error message
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// IssuerPublicKey defines model for IssuerPublicKey.
type IssuerPublicKey struct {
	// Algorithm Signing algorithm identifier
	Algorithm string    `json:"algorithm"`
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique key identifier
	Id string `json:"id"`

	// PublicKey Base64-encoded BLS12-381 G2 public key (96 bytes)
	PublicKey []byte     `json:"publicKey"`
	RotatedAt *time.Time `json:"rotatedAt,omitempty"`
}

// VerifyCaptchaProofRequest defines model for VerifyCaptchaProofRequest.
type VerifyCaptchaProofRequest struct {
	// Domain Domain of the requesting website
	Domain string `json:"domain"`

	// Nonce Session nonce used during proof generation
	Nonce string `json:"nonce"`

	// Proof Base64url-encoded proof envelope from the NaughtBot SDK
	Proof string `json:"proof"`
}

// VerifyCaptchaProofResponse defines model for VerifyCaptchaProofResponse.
type VerifyCaptchaProofResponse struct {
	Attestation *CaptchaAttestation `json:"attestation,omitempty"`

	// Error Human-readable error message (present when valid is false)
	Error *string `json:"error,omitempty"`

	// Valid Whether the proof is valid
	Valid bool `json:"valid"`
}

// CredentialsVerifyCaptchaProofJSONRequestBody defines body for CredentialsVerifyCaptchaProof for application/json ContentType.
type CredentialsVerifyCaptchaProofJSONRequestBody = VerifyCaptchaProofRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CredentialsGetPublicKeys request
	CredentialsGetPublicKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CredentialsVerifyCaptchaProofWithBody request with any body
	CredentialsVerifyCaptchaProofWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CredentialsVerifyCaptchaProof(ctx context.Context, body CredentialsVerifyCaptchaProofJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthGet request
	HealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CredentialsGetPublicKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCredentialsGetPublicKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CredentialsVerifyCaptchaProofWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCredentialsVerifyCaptchaProofRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CredentialsVerifyCaptchaProof(ctx context.Context, body CredentialsVerifyCaptchaProofJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCredentialsVerifyCaptchaProofRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCredentialsGetPublicKeysRequest generates requests for CredentialsGetPublicKeys
func NewCredentialsGetPublicKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/credentials/public-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCredentialsVerifyCaptchaProofRequest calls the generic CredentialsVerifyCaptchaProof builder with application/json body
func NewCredentialsVerifyCaptchaProofRequest(server string, body CredentialsVerifyCaptchaProofJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCredentialsVerifyCaptchaProofRequestWithBody(server, "application/json", bodyReader)
}

// NewCredentialsVerifyCaptchaProofRequestWithBody generates requests for CredentialsVerifyCaptchaProof with any type of body
func NewCredentialsVerifyCaptchaProofRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/credentials/verify-proof")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthGetRequest generates requests for HealthGet
func NewHealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CredentialsGetPublicKeysWithResponse request
	CredentialsGetPublicKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CredentialsGetPublicKeysResponse, error)

	// CredentialsVerifyCaptchaProofWithBodyWithResponse request with any body
	CredentialsVerifyCaptchaProofWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CredentialsVerifyCaptchaProofResponse, error)

	CredentialsVerifyCaptchaProofWithResponse(ctx context.Context, body CredentialsVerifyCaptchaProofJSONRequestBody, reqEditors ...RequestEditorFn) (*CredentialsVerifyCaptchaProofResponse, error)

	// HealthGetWithResponse request
	HealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthGetResponse, error)
}

type CredentialsGetPublicKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]IssuerPublicKey
}

// Status returns HTTPResponse.Status
func (r CredentialsGetPublicKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CredentialsGetPublicKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CredentialsVerifyCaptchaProofResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VerifyCaptchaProofResponse
	JSON400      *ErrorResponse
	JSON401      *VerifyCaptchaProofResponse
}

// Status returns HTTPResponse.Status
func (r CredentialsVerifyCaptchaProofResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CredentialsVerifyCaptchaProofResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CredentialsGetPublicKeysWithResponse request returning *CredentialsGetPublicKeysResponse
func (c *ClientWithResponses) CredentialsGetPublicKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CredentialsGetPublicKeysResponse, error) {
	rsp, err := c.CredentialsGetPublicKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCredentialsGetPublicKeysResponse(rsp)
}

// CredentialsVerifyCaptchaProofWithBodyWithResponse request with arbitrary body returning *CredentialsVerifyCaptchaProofResponse
func (c *ClientWithResponses) CredentialsVerifyCaptchaProofWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CredentialsVerifyCaptchaProofResponse, error) {
	rsp, err := c.CredentialsVerifyCaptchaProofWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCredentialsVerifyCaptchaProofResponse(rsp)
}

func (c *ClientWithResponses) CredentialsVerifyCaptchaProofWithResponse(ctx context.Context, body CredentialsVerifyCaptchaProofJSONRequestBody, reqEditors ...RequestEditorFn) (*CredentialsVerifyCaptchaProofResponse, error) {
	rsp, err := c.CredentialsVerifyCaptchaProof(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCredentialsVerifyCaptchaProofResponse(rsp)
}

// HealthGetWithResponse request returning *HealthGetResponse
func (c *ClientWithResponses) HealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthGetResponse, error) {
	rsp, err := c.HealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthGetResponse(rsp)
}

// ParseCredentialsGetPublicKeysResponse parses an HTTP response from a CredentialsGetPublicKeysWithResponse call
func ParseCredentialsGetPublicKeysResponse(rsp *http.Response) (*CredentialsGetPublicKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CredentialsGetPublicKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []IssuerPublicKey
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCredentialsVerifyCaptchaProofResponse parses an HTTP response from a CredentialsVerifyCaptchaProofWithResponse call
func ParseCredentialsVerifyCaptchaProofResponse(rsp *http.Response) (*CredentialsVerifyCaptchaProofResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CredentialsVerifyCaptchaProofResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VerifyCaptchaProofResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest VerifyCaptchaProofResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseHealthGetResponse parses an HTTP response from a HealthGetWithResponse call
func ParseHealthGetResponse(rsp *http.Response) (*HealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
